geostyler/geostyler

- package-lock.json
- package.json
This adds `ts-jest` as a devDependency:
Known issue in create-react-app-typescript:
https://github.com/wmonk/create-react-app-typescript/issues/198
> Fixes tests

- README.md
This reworks the autogenerated project README a bit:
- Add title and subtitle
- Add badge for build status (from Travis CI)
- Add a section for related projects (DataParser, Declartion Files, ...)
> Minor additions to README

- package.json
> chore(package): update react-styleguidist to version 7.0.13

- package.json
> chore(package): update @types/node to version 10.0.9

- package.json
- src/Component/FieldSet/FieldSet.css
- src/Component/FieldSet/FieldSet.tsx
- src/Component/Filter/AttributeCombo/AttributeCombo.tsx
- src/Component/Filter/BoolFilterField/BoolFilterField.tsx
- src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
- src/Component/Filter/NumberFilterField/NumberFilterField.tsx
- src/Component/Filter/OperatorCombo/OperatorCombo.tsx
- src/Component/Filter/TextFilterField/TextFilterField.tsx
- src/Component/Rule/NameField/NameField.css
- src/Component/Rule/NameField/NameField.tsx
- src/Component/Rule/RemoveButton/RemoveButton.css
- src/Component/Rule/RemoveButton/RemoveButton.tsx
- src/Component/Rule/Rule.css
- src/Component/Rule/Rule.tsx
- src/Component/Rule/TitleField/TitleField.css
- src/Component/Rule/TitleField/TitleField.tsx
- src/Component/ScaleDenominator/MaxScaleDenominator.css
- src/Component/ScaleDenominator/MaxScaleDenominator.tsx
- src/Component/ScaleDenominator/MinScaleDenominator.css
- src/Component/ScaleDenominator/MinScaleDenominator.tsx
- src/Component/ScaleDenominator/ScaleDenominator.tsx
- src/Component/Symbolizer/Preview/Preview.tsx
- src/app/App.tsx
- src/app/Demo/Rule/RuleDemo.tsx
This introduces several React components to model a Rule-GUI.
The symbolizer GUI is not implemented yet and will be part of a follow-up PR (see issues #81 and #82).
A demo GUI showing the functionality is also part of this PR:
> Implement a Rule GUI

- package-lock.json
- package.json
This removes `geostyler-data` from devDependencies as it is already included in the dependencies with a version tag.
> Removes geostyler-data from devDependencies

- package.json
> fix(package): update antd to version 3.5.4

- package.json
> chore(package): update np to version 3.0.1

- src/app/Demo/Rule/RuleDemo.tsx
> Add missing name to GeoStyler Style in RuleDemo

- README.md
> Add geostyler-wfs-parser to list of DataParser implementations

- package-lock.json
- package.json
- src/Component/DataInput/DataLoader/DataLoader.tsx
- src/Component/DataInput/StyleLoader/StyleLoader.tsx
- src/Component/Filter/AttributeCombo/AttributeCombo.tsx
- src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
- src/Component/NameField/NameField.css
- src/Component/NameField/NameField.spec.tsx
- src/Component/NameField/NameField.tsx
- src/Component/Rule/NameField/NameField.css
- src/Component/Rule/RemoveButton/RemoveButton.tsx
- src/Component/Rule/Rule.tsx
- src/Component/ScaleDenominator/MaxScaleDenominator.tsx
- src/Component/ScaleDenominator/MinScaleDenominator.tsx
- src/Component/ScaleDenominator/ScaleDenominator.tsx
- src/Component/Style/Style.tsx
- src/Component/Symbolizer/Editor/Editor.tsx
- src/Component/Symbolizer/Preview/Preview.tsx
- src/Component/UploadButton/UploadButton.tsx
- src/app/App.css
- src/app/App.tsx
- src/app/Demo/FilterUi/FilterDemo.tsx
- src/app/Demo/Rule/RuleDemo.tsx
This is a quite big PR that introduces and refactors UI Components.
New components:
- `Style` UI Component that creates the Editor UI for a GeoStyler Style `Style`
- `StyleLoader` UI to allow loading of `Style` Files
- `DataLoader` UI to allow loading of `Data` Files
The refactoring was made to ensure that every UI Component can handle its GeoStyler-Style representation on instantiation aswell as on update.
Refactored components:
- `AttributeCombo`
- `ComparisonFilter`
- `NameField` --> Moved from rule to root as it can be reused for Style
- `Rule`
- `ScaleDenominator`, `MinScaleDenominator`, `MaxScaleDenominator`
- `Preview`
- `Editor`
- `UploadButton`
This also makes the App.tsx to not include one of the demos anymore but be the first very basic version of the GeoStyler as a standalone …
> UI enhancements

- package.json
> chore(package): update np to version 3.0.4

- package.json
> chore(package): update react-styleguidist to version 7.0.16

- src/Component/Filter/AttributeCombo/AttributeCombo.spec.tsx
- src/Component/Filter/AttributeCombo/AttributeCombo.tsx
- src/Component/Filter/ComparisonFilter/ComparisonFilter.spec.tsx
- src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
> Filter selectable attributes in AttributeCombo by a filter function

- .travis.yml
- package-lock.json
- package.json
- styleguide.config.js
- tsconfig.json
This introduces stylegudist. 
Closes #59
> Introduces styleguidist config

- .ci/update-gh-pages.sh
- .travis.yml
This removes `> /dev/null 2>&1` from travis.yml for debugging purpose.
> Debug travis

- package.json
> chore(package): update @types/jest to version 23.0.2

- package-lock.json
- src/Component/ScaleDenominator/ScaleDenominator.tsx
>  Fix typo in ScaleDenominator API docs

- src/Component/Filter/BoolFilterField/BoolFilterField.tsx
- src/Component/Filter/NumberFilterField/NumberFilterField.tsx
Fixes #173 - NumberFilterField
- Fixed import of `Form.Item`
- Removed min and max value as this should be moved to the validation and should not just block the numberspinner.
Fixes #171 - BoolFilterField
- Ensure that the passed checked prop is boolean
> Fixes issues with BoolFilterField and NumberFilterField

- src/Component/Filter/ComparisonFilter/ComparisonFilter.spec.tsx
- src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
- src/Component/Filter/NumberFilterField/NumberFilterField.spec.tsx
- src/Component/Filter/TextFilterField/TextFilterField.spec.tsx
- tsconfig.json
Fixes bugs reported in https://github.com/terrestris/geostyler/issues/182 and adds some tests
> ComparisonFilter: Validation bug fixes and tests

- public/index.html
- public/style.css
This adds links to [imprint](https://www.terrestris.de/en/impressum/) and [privacy](https://www.terrestris.de/en/datenschutzerklaerung) to the GitHub Pages Demo App.
> Adds links to imprint and privacy to App

- src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
> Move call of onValidationChanged to callback of setState

- package.json
> fix(package): update geostyler-openlayers-parser to version 0.5.0

- package.json
> chore(package): update @types/react to version 16.4.1

- src/index.js
> Export editors in index.js

- README.md
Information about handling `npm link` problems was added to README.
resolves #318
> Add info about setting up development environment

- src/Component/Filter/AttributeCombo/AttributeCombo.tsx
- src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
> Adds attribute name mapping function

- package.json
> Greenkeeper/monorepo.enzyme 3.4.4

- package.json
> chore(package): update react-docgen-typescript to version 1.7.0

- README.md
> Add link to documentation to readme

- package.json
> fix(package): update antd to version 3.9.2

- package.json
> update geostyler-openlayers-parser to v0.14.1

- package.json
> chore(package): update react-styleguidist to version 7.3.8

- src/Component/Symbolizer/Preview/Preview.tsx
> Adds callback function `onMapDidMount`

- package.json
> chore(package): update @types/react to version 16.4.17

- browser-build.config.js
- package.json
> Adds babel polyfill for IE support

- src/Component/Filter/ComparisonFilter/ComparisonFilter.css
- src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
- src/Component/Filter/FilterTree/FilterTree.css
- src/Component/Filter/FilterTree/FilterTree.spec.tsx
- src/Component/Filter/FilterTree/FilterTree.tsx
- src/Component/Rule/Rule.tsx
- src/Util/TestUtil.tsx
- src/app/data/TemplateStyle.ts
- tsconfig.json
This introduces the `FilterTree` Component.
It adds support for editing complex/interleaved filters.
TODO:
~~- [ ] Refactor `TreeNode`s to new component~~ Canceld as there is to much shared code
> Introduces FilterTree for complex filters

- browser-build.config.js
- package.json
> Fix browser build

- src/Component/Symbolizer/Preview/Preview.spec.tsx
Preview component was missing a few required props. Added these.
> Fix preview spec

- package.json
- src/Component/Filter/FilterTree/FilterTree.spec.tsx
- src/app/Demo/FilterUi/FilterDemo.tsx
- src/app/Demo/Rule/RuleDemo.tsx
Now using react-scripts-ts version 3.1.0 and typescript version 3.1.4.
Also made small lint fixes.
This PR should replace #449
> Update react-scripts-ts and typescript

- package.json
> chore(package): update @types/node to version 10.12.5

- package.json
> fix(package): update antd to version 3.10.7

- src/Component/Style/Style.tsx
- src/Component/Symbolizer/BulkEditModals/BulkEditModals.tsx
- src/index.js
- src/locale/de_DE.js
- src/locale/en_US.js
> Implement multi rule editor for color, radius and opacity

- styleguide.config.js
> Add RuleGenerator and RuleGeneratorWindow to styleguide

- package.json
> chore(package): update @types/react to version 16.7.6

- src/Component/Style/Style.tsx
Title says it all.
Plz review.
> Add prop to Style to en/disable classification tool

- src/Component/Filter/FilterEditorWindow/FilterEditorWindow.tsx
- src/Component/Filter/FilterTree/FilterTree.tsx
- src/Component/RuleTable/RuleTable.tsx
- src/Component/Style/Style.tsx
Especially:
* FilterUiProps for attribute and operator name mappings
* The data definition and specification
* The renderer type
Depends on #610 
Plz review @terrestris/devs
> Pass futher props to FilterTree and FilterEditorWindow

- src/Component/CodeEditor/CodeEditor.tsx
- src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
- src/Component/Filter/FilterTree/FilterTree.tsx
- src/Component/RuleTable/RuleTable.spec.tsx
- src/Component/RuleTable/RuleTable.tsx
- src/Component/Style/Style.tsx
- src/Component/Symbolizer/Editor/Editor.tsx
> Introduces componentDidCatch to some main components

- src/Component/CodeEditor/CodeEditor.tsx
This makes the save button in the code editor optional.
> Makes save button optional

- src/Component/RuleTable/RuleTable.tsx
- src/Component/Symbolizer/Editor/Editor.tsx
- src/Component/Symbolizer/MultiEditor/MultiEditor.tsx
- src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.tsx
- src/Component/Symbolizer/TextEditor/TextEditor.spec.tsx
- src/Component/Symbolizer/TextEditor/TextEditor.tsx
- src/locale/de_DE.js
- src/locale/en_US.js
Also makes sure the data is actually available in many editors/fields.
> Adds attribute suggestions when typing {{

- package.json
> fix(package): update geostyler-sld-parser to version 0.18.0

- package.json
> fix(package): update geostyler-openlayers-parser to version 0.19.2

- src/Component/RuleTable/RuleTable.tsx
> Add Popover to Rulename cells

- src/index.js
- src/locale/es_ES.js
Translation to Spanish language
> Add spanish locale translation

- package.json
> chore(package): update @types/react to version 16.7.13

- package.json
> chore(package): update antd to version 3.11.2

- package.json
> chore(package): update webpack to version 4.27.1

- src/Component/RuleTable/RuleTable.tsx
- src/Component/Style/Style.tsx
> RuleTable: Make visibility of columns for duplicates and amount configurable

- package.json
> chore(package): update terser-webpack-plugin to version 1.2.1

- src/Component/RuleGenerator/RuleGeneratorWindow.tsx
- src/Component/Style/Style.tsx
Title says it all.
@KaiVolland Please review.
> Passes down color ramps to rule generator

- package.json
> chore(package): update antd to version 3.12.3

- package.json
- src/Component/RuleGenerator/ClassificationCombo/ClassificationCombo.tsx
- src/Component/RuleGenerator/ColorRampCombo/ColorRampCombo.tsx
- src/Component/RuleGenerator/ColorSpaceCombo/ColorSpaceCombo.tsx
- src/Component/RuleTable/RuleTable.tsx
- src/Util/FilterUtil.spec.ts
- src/Util/FilterUtil.ts
This introduces the `geostyler-cql-parser` and replaces the `writeAsCql` method from the `FilterUtil`.
Closes #757
> Introduce geostyler-cql-parser

- package.json
> fix(package): update react-rnd to version 9.1.1

- src/Component/RuleGenerator/RuleGenerator.tsx
- src/Component/RuleGenerator/RuleGeneratorWindow.tsx
- src/Component/Style/Style.tsx
Adds a flag to the styler component to merge the custom color ramps with the chroma-js brewer ramps.
> Adds flag to have custom color ramps plus the brewer ones

- jest/setup.js
- package.json
- src/Component/DataInput/StyleLoader/StyleLoader.spec.tsx
- src/Component/DataInput/StyleLoader/StyleLoader.tsx
- src/Component/FieldSet/FieldSet.spec.tsx
- src/Component/NameField/NameField.spec.tsx
- src/Component/Rule/TitleField/TitleField.spec.tsx
- src/Component/RuleTable/RuleTable.spec.tsx
- src/Component/RuleTable/RuleTable.tsx
- src/Component/ScaleDenominator/ScaleDenominator.spec.tsx
- src/Component/ScaleDenominator/ScaleDenominator.tsx
- src/Component/Symbolizer/Field/ColorField/ColorField.spec.tsx
- src/Component/Symbolizer/Field/ColorField/ColorField.tsx
- src/Component/Symbolizer/Field/ImageField/ImageField.spec.tsx
- src/Component/Symbolizer/Field/LineDashField/LineDashField.spec.tsx
- src/Component/Symbolizer/Field/LineDashField/LineDashField.tsx
- src/Component/Symbolizer/IconSelectorWindow/IconSelectorWindow.spec.tsx
- src/Component/Symbolizer/IconSelectorWindow/IconSelectorWindow.tsx
- src/Component/UploadButton/UploadButton.tsx
- src/Util/HTTPUtil.spec.ts
- src/Util/HTTPUtil.ts
This adds a some tests to reincrease the coverage a little. Still a lot of untested lines…
> More tests

- src/Component/Symbolizer/TextEditor/TextEditor.css
- src/locale/de_DE.ts
- src/locale/en_US.ts
- src/locale/es_ES.ts
> Fix text editor labels

- src/Util/FilterUtil.spec.ts
- src/Util/FilterUtil.ts
> Ignore scale denominators when calculating duplicates

- src/Component/CodeEditor/CodeEditor.tsx
Allows parser instances to be specified in the parser list in order to be able to construct parsers with options.
> Allow parser instances instead of constructor functions

- package.json
> chore(package): update enzyme-adapter-react-16 to version 1.11.2

- package.json
> chore(package): update @babel/preset-env to version 7.4.2

- package.json
> chore(package): update enzyme-adapter-react-16 to version 1.12.1

- package.json
> chore(package): update fork-ts-checker-webpack-plugin to version 1.2.0

- package.json
> chore(package): update antd to version 3.17.0

- package.json
> fix(package): update @types/react to version 16.8.16

- package.json
> chore(package): update fork-ts-checker-webpack-plugin to version 1.3.2

- package.json
> chore(package): update react-styleguidist to version 9.1.2

- package.json
> chore(package): update antd to version 3.19.1

- package.json
> chore(package): update react-styleguidist to version 9.1.4

- .github/ISSUE_TEMPLATE/geostyler-parser.md
> Include QGIS and CQL in issue template

- package.json
> chore(package): update antd to version 3.19.5

- package.json
> chore(package): update fork-ts-checker-webpack-plugin to version 1.3.7

- package-lock.json
- package.json
- src/Component/Symbolizer/TextEditor/TextEditor.spec.tsx
- src/Component/Symbolizer/TextEditor/TextEditor.tsx
This updates `antd` to version ~3.19.8.
It also replaces the deprecated `Mention` component with the new `Mentions` component.
@terrestris/devs please review
> Updates antd and replaces deprecated `Mention`

- .ci/update-gh-pages.sh
This updates `update-gh-pages.sh` to renable the automatic deployment of the docs.
> Changes to update-gh-pages.sh

- src/Component/RuleTable/RuleReorderButtons/RuleReorderButtons.tsx
Enable i18n for `RuleReorderButtons` component.
Fixes #1151
> Fix i18n for RuleReorderButtons

- browser-build.config.js
- docs/README.md
- package-lock.json
- src/Component/Symbolizer/Field/ColorField/ColorField.tsx
- styleguide.config.js
- tsconfig.json
This updates some styleguide related configs.
It includes needed changes to `browser-build.config.js` and `ColorField.tsx ` to work with the latest package updates.
> Updates styelguide related configs

- README.md
- docs/README.md
> Fix link to v4.3.0 in README

- .github/ISSUE_TEMPLATE/geostyler-docs.md
We do have several issues regarding our documentation. Added a template to easier categorise these issues.
> Create geostyler-docs issue template

- src/Component/CodeEditor/CodeEditor.tsx
- src/Component/DataInput/DataLoader/DataLoader.tsx
- src/Component/DataInput/StyleLoader/StyleLoader.tsx
- src/Component/DataInput/WfsParserInput/WfsParserInput.tsx
- src/Component/Filter/FilterEditorWindow/FilterEditorWindow.tsx
- src/Component/Filter/FilterTree/FilterTree.tsx
- src/Component/NameField/NameField.tsx
- src/Component/Rule/Rule.tsx
- src/Component/RuleGenerator/ClassificationCombo/ClassificationCombo.tsx
- src/Component/RuleGenerator/ColorRampCombo/ColorRampCombo.tsx
- src/Component/RuleGenerator/ColorSpaceCombo/ColorSpaceCombo.tsx
- src/Component/RuleGenerator/ColorsPreview/ColorsPreview.tsx
- src/Component/RuleGenerator/RuleGenerator.tsx
- src/Component/RuleTable/RuleReorderButtons/RuleReorderButtons.tsx
- src/Component/RuleTable/RuleTable.tsx
- src/Component/ScaleDenominator/MaxScaleDenominator.tsx
- src/Component/ScaleDenominator/MinScaleDenominator.tsx
- src/Component/ScaleDenominator/ScaleDenominator.tsx
- src/Component/Style/Style.tsx
> Add property descriptions of some Components

- src/Component/DataInput/DataLoader/DataLoader.spec.tsx
- src/Component/DataInput/DataLoader/DataLoader.tsx
- src/Component/UploadButton/UploadButton.tsx
This adds handling of Shapefiles to the `DataLoader`.
> Adds Shapefile support to DataLoader

- src/locale/zh_CN.ts
Thank you for considering giving code and/or documentation back to this project, you're awesome and we appreciate your work.
Please review the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md) of this repository. This makes it easy for you to give back and for us to accept your changes.
Please use the template below the line for the pull request description, and make sure to tick off the boxes in the checklists. In your final pull request everything above the next horizontal line can be removed to not distract reviewers or other readers.
Again: thank you for your contribution.
------------
This PR adds basic zh-CN locale support to components and …
> Add locale zh-CN

- .github/pull_request_template.md
This PR suggests to add a type 'dependecy updates' to the list of PR types in the pull request template.
None.
> Add PR-type 'dependency updates'

- src/index.ts
Export component `ColorMapEditor` to index.
> Export ColorMapEditor

- src/index.ts
This adds FilterTree Component to the export list on the base index.js, which was missing.
Added a missing export class or function
> Added FilterTree to the list of exportable components

- package-lock.json
- src/Component/Filter/FilterTree/FilterTree.tsx
- src/Component/RuleTable/RuleTable.less
This enables the remove Button for the first filter in the RuleTable. Additonally the edit button is always shown in the table.
Includes a new `package-lock.json` created with `npm audit fix` to remove som vulnerablities.
Fixes #1039
> Allow filter delete

- .github/workflows/on-push-master.yml
Bugfix for the github actions.
> Fixes test command

- .github/pull_request_template.md
This fixes a minor typo in the PR template.
--
> Fix type in PR template

- package.json
> Bump np from 6.4.0 to 7.4.0

- dev-build.config.js
This fixes the browser build dev setup.
> Fix browser build dev setup

- .github/workflows/on-pull-request.yml
This PR suggests to determine and report the test coverage also for PRs, not oly for merges onto master.
- ~~[ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)~~ n.a.
> Determine and report test coverage also for PRs

- package-lock.json
- package.json
- src/Component/CodeEditor/CodeEditor.less
- src/Component/CodeEditor/CodeEditor.spec.tsx
- src/Component/CodeEditor/CodeEditor.tsx
- src/Component/Legacy/CodeEditor/CodeEditor.less
- src/Component/Legacy/CodeEditor/CodeEditor.spec.tsx
- src/Component/Legacy/CodeEditor/CodeEditor.tsx
- src/hook/UsePrevious.tsx
- src/index.ts
- tsconfig.json
This replaces the editor used for the `CodeEditor` component.
[Code-Mirror](https://codemirror.net/) is replaced with [Monaco-Editor](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults) wrapped by [`@monaco-editor/react`](https://www.npmjs.com/package/@monaco-editor/react).
The monaco-editor comes with tons of extra features and optional plugins. For example, we can use the new geostyler-style JSON schema (https://github.com/geostyler/geostyler-style/pull/154) to validate, document and autocomplete the entered geostyler-style.
The old code-mirror editor is not removed completly but moved to the `Legacy` folder in components.
As this PR relies on https://github.com/geostyler/geostyler-style/pull/154 (and a corresponding release) it …
> Introduces monaco-editor

- package-lock.json
- package.json
Reverts geostyler/geostyler#1404
> Revert "Bump css-loader from 3.6.0 to 5.2.0"

- .github/workflows/on-publish.yml
- .github/workflows/on-push-master.yml
This fixes on-publish and on-push-master workflows.
> Fixes on-publish and on-push-master workflows

- src/index.ts
Adds missing export of chinese locale to index.ts
> Adds chinese locale to index.ts

- package-lock.json
- package.json
- src/Component/LocaleWrapper/LocaleWrapper.tsx
This fixes the `LocaleWrapper` by updating to the new `Context` API of react.
Please be aware that you should update the config provider import in your project to:
`import ConfigProvider from 'antd/lib/config-provider';` as their seems to be difficulties when importing from antd root.
Compare https://github.com/geostyler/geostyler-demo/pull/221
When working with npm link and webpack you'll even need to add an alias for antd to your webpack config.
closes #1417 
> Locale wrapper fix

- README.md
Add more links to related projects / parsers
> Add more links to the README

- src/Component/DataInput/WfsParserInput/WfsParserInput.tsx
- src/Component/FieldSet/FieldSet.tsx
- src/Component/Filter/AttributeCombo/AttributeCombo.spec.tsx
- src/Component/Filter/AttributeCombo/AttributeCombo.tsx
- src/Component/Filter/BoolFilterField/BoolFilterField.spec.tsx
- src/Component/Filter/BoolFilterField/BoolFilterField.tsx
- src/Component/Filter/ComparisonFilter/ComparisonFilter.spec.tsx
- src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
- src/Component/Filter/FilterEditorWindow/FilterEditorWindow.tsx
- src/Component/Filter/FilterEditorWindow/FilterWindow.spec.tsx
- src/Component/Filter/FilterTree/FilterTree.spec.tsx
- src/Component/Filter/FilterTree/FilterTree.tsx
- src/Component/Filter/NumberFilterField/NumberFilterField.spec.tsx
- src/Component/Filter/NumberFilterField/NumberFilterField.tsx
- src/Component/Filter/OperatorCombo/OperatorCombo.spec.tsx
- src/Component/Filter/OperatorCombo/OperatorCombo.tsx
- src/Component/Filter/TextFilterField/TextFilterField.spec.tsx
- src/Component/Filter/TextFilterField/TextFilterField.tsx
- src/Component/RuleTable/RuleTable.tsx
- src/Util/FilterUtil.spec.ts
- src/Util/FilterUtil.ts
This transforms the `Filter` and `FieldSet` components to function components.
> Transform Filter components to function components

- custom.d.ts
- package-lock.json
- package.json
- src/Component/NameField/NameField.spec.tsx
- src/Component/NameField/NameField.tsx
- src/Component/Symbolizer/Preview/Preview.tsx
- tsconfig.json
This updates the ol devDependency to use `^6.8.1` and removes the custom types for the ol package.
It also makes the `NameField` a function component.
> Update ol and use ol types

- src/Component/Selectable/Selectable.example.md
- src/Component/Selectable/Selectable.spec.tsx
- src/Component/Selectable/Selectable.tsx
- src/Component/Selectable/SelectableItem/SelectableItem.less
- src/Component/Selectable/SelectableItem/SelectableItem.spec.tsx
- src/Component/Selectable/SelectableItem/SelectableItem.tsx
- src/index.ts
- styleguide.config.js
Thank you for considering giving code and/or documentation back to this project, you're awesome and we appreciate your work.
Please review the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md) of this repository. This makes it easy for you to give back and for us to accept your changes.
Please use the template below the line for the pull request description, and make sure to tick off the boxes in the checklists. In your final pull request everything above the next horizontal line can be removed to not distract reviewers or other readers.
Again: thank you for your contribution.
------------
Please give a short description of the changes you …
> Introduce Selectable

- src/Component/Breadcrumb/Breadcrumb.spec.tsx
> Breadcrumb test

- src/Component/Removable/Removable.example.md
- src/Component/Removable/Removable.spec.tsx
- src/Component/Removable/Removable.tsx
- src/Component/Removable/RemovableItem/RemovableItem.less
- src/Component/Removable/RemovableItem/RemovableItem.spec.tsx
- src/Component/Removable/RemovableItem/RemovableItem.tsx
- src/index.ts
- styleguide.config.js
Thank you for considering giving code and/or documentation back to this project, you're awesome and we appreciate your work.
Please review the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md) of this repository. This makes it easy for you to give back and for us to accept your changes.
Please use the template below the line for the pull request description, and make sure to tick off the boxes in the checklists. In your final pull request everything above the next horizontal line can be removed to not distract reviewers or other readers.
Again: thank you for your contribution.
------------
Please give a short description of the changes you …
> Introduce Removable

- package-lock.json
- package.json
- src/Component/CodeEditor/CodeEditor.tsx
- src/Component/Symbolizer/Renderer/Renderer.tsx
This fixes the `Renderer` (openlayers) and the `CodeEditor`.
> Fix Renderer and CodeEditor

- webpack.browser.config.js
> Add missing css loader

- package-lock.json
- package.json
- src/Component/DataInput/WfsParserInput/WfsParserInput.spec.tsx
- src/Component/Filter/TextFilterField/TextFilterField.tsx
This updates antd to the latest v4.20.5.
It also adds a workaround to a test which is needed due to this bug in antd:
https://github.com/ant-design/ant-design/issues/35600
Actually this is a good example why testing input elements via className is a bad idea. Maybe adding a test-id to the Element would be a better idea. :)
closes #1662
> Update antd to v4.20.5

- src/Component/CodeEditor/CodeEditor.tsx
- src/Component/FieldSet/FieldSet.tsx
- src/Component/PreviewMap/PreviewMap.tsx
- src/Component/Rule/RemoveButton/RemoveButton.tsx
- src/Component/Rule/Rule.tsx
- src/Component/RuleGenerator/RuleGenerator.tsx
- src/Component/RuleTable/RuleReorderButtons/RuleReorderButtons.tsx
- src/Component/RuleTable/RuleTable.tsx
- src/Component/Style/Style.tsx
- src/Component/Symbolizer/Editor/Editor.tsx
- src/Component/Symbolizer/Preview/Preview.tsx
- src/DataProvider/DataProvider.ts
- src/Util/FilterUtil.ts
- src/Util/HTTPUtil.ts
This fixes some small typos and other minor wording issues.
--
> Fix several spelling errors in src/

- src/Component/Symbolizer/Renderer/Renderer.tsx
This fixes the renderer component. Due to the refactoring of class to function components, the renderer did not work as expected.
I.e. on every symbolizer change, a new map instance was created. This was caused by a `useEffect` that handled multiple effects.
This PR splits the different effects into separate functions.
--
> Fix renderer component

- README.md
This removes the info about the Code Sprint from the README.
None
> Remove Info about Code Sprint from README

- .github/workflows/on-publish.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-main.yml
- package.json
This updates node versions in the CI process:
- It replaces v12 with v18 in the "on-pull-request" workflow.
- It replaces v14 with v16 in the "publish" and "push-main" workflows.
It also updates @types/node to v18.
Please list issues or pull requests that the changes you propose are related to. It does not matter if they are still open and/or unmerged, any link is appreciated.
> Update node versions

- src/locale/fr_FR.ts
Translates remaining strings highlighted as TODO in the french locale file and modifies a few other strings that were forgotten in the first translation.
Missing translations highlighted by @KaiVolland for issue https://github.com/geostyler/geostyler/issues/1751
> French translation complements

- .releaserc
> Fix copy/paste left-over in .releaserc

- src/Component/Filter/AttributeCombo/AttributeCombo.tsx
- src/Component/Filter/BoolFilterField/BoolFilterField.tsx
- src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
- src/Component/Filter/FilterTree/FilterTree.tsx
- src/Component/Filter/NumberFilterField/NumberFilterField.tsx
- src/Component/Filter/TextFilterField/TextFilterField.tsx
- src/Component/Symbolizer/PropTextEditor/PropTextEditor.tsx
- src/locale/de_DE.ts
- src/locale/en_US.ts
- src/locale/es_ES.ts
- src/locale/fr_FR.ts
- src/locale/locale.ts
- src/locale/zh_CN.ts
This PR adds translation to the FilterEditor components in cases where it was not yet linked or available.
As part of this adjustment, the properties of some components have changed. The labels are now no longer set via a props keyword but are taken from the translation files. Remove these props if the affected components are used directly:
- **AttributeCombo**
- props `label` and `placeholder` got removed
- **ComparisonFilter**
- props `attributeLabel` `attributePlaceholderString` `attributeValidationHelpString` `valueLabel` and `valuePlaceholder` got removed
- **NumberFilterField**
- props `label` and `placeholder` got removed
- **TextFilterField**
- props `label` and `placeholder` got removed
This PR is related to https://github.com/geostyler/geostyler/issues/1834
Please check the type …
> Applies translations to FilterEditor

- package-lock.json
- package.json
- src/Component/DataInput/DataLoader/DataLoader.tsx
- src/Component/DataInput/WfsParserInput/WfsParserInput.spec.tsx
- src/Component/DataInput/WfsParserInput/WfsParserInput.tsx
This updates the `geostyler-wfs-parser` to version 2.0.0.
:exclamation: Breaking changes:
- Some version have been removed from the `WfsParserInput`
- Signature of `onClick` has been changed
> Updates `geostyler-wfs-parser`

- .github/workflows/commitlint.yml
- .github/workflows/dev-setup-working.yml
- .github/workflows/on-publish.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-main.yml
- .github/workflows/release.yml
This makes use of the newest version of the checkout action.
> Make use of actions/checkout@v3

- src/locale/fr_FR.ts
Adding 3 missing translations in french.
> translating 3 todos in fr

- CONTRIBUTING.md
- README.md
This adds infos about the commit message formatting and the usage of styleguidist for develpment to README and CONTRIBUTING.md.
fixes https://github.com/geostyler/geostyler/issues/1999
> docs: add info about commit message formatting

- src/Component/DragDroppable/DragDroppable.example.md
This updates the `<DragDroppable />` example to fit it's actual API.
None
> docs: update DragDroppable example to match latest API

- README.md
BREAKING CHANGE: This forces a major release for a previously wrongly formatted commit message (commit sha 30e19de16a6310dcd79bf4e4292b33bf80004c0d) that lead to the unintended release of version 10.3.1, which includes a breaking change. The code of this release will be identical with the code of version 10.3.1.
None
> breaking: force major release

- .github/workflows/release.yml
- README.md
This makes use of the semantic-release-action and adds an action to update the links to the documentation.
> Auto update documentation links in README.md

- jest/setup.js
- package-lock.json
- package.json
Updatges geostyler-openlayers-parser
> build(deps): update geostyler-openlayers-parser

- src/context/GeoStylerContext/GeoStylerContext.tsx
This introduces the new `GeoStylerContext` which will cover several funtionalities that have been split before:
- locale
- defaultValues
- unsupportedProperties
- composition
This will be reused in the harmonization branch (#1998).
Discussion: #2052 
Related issue: #1971 
> Introduces new GeoStylerContext

- package-lock.json
- package.json
- src/Component/Symbolizers/Symbolizers.tsx
This removes some artifacts of `react-dnd`, which is not being used anymore. This also removes `react-dnd` dependencies from package.json
> refactor: remove unused artifacts of react-dnd

- README.md
This introduces the discord badge:
[![Discord](https://img.shields.io/discord/1016992288028762132?style=plastic)](https://discord.gg/8rtc8USE)
to the README.md
> docs: add discord badge to readme

- .github/workflows/stale.yml
This updates the messages of the stale bot.
> ci: update stale bot messages

- .releaserc
This uses the conventionalcommits configuration for semantic releases. Through this, commit linting and release process should be in synch.
> chore: use conventionalcommits in release configuration

- jest.config.js
- package-lock.json
- package.json
Improves test performance by updating jsdom and configuring jest with `workerThreads: true`.
@geostyler/sprinters @geostyler/devs Please review.
> fix: improve test performance

- vite.dev.config.ts
> refactor: add missing semicolons to vite config

- src/Component/Style/Style.example.md
This adds an illustrative icon library configuration to the `Style` example.
Please review @geostyler/devs.
> docs: include the icon library to the example

- src/locale/fr_FR.ts
These are simple changes in french translations
> fix: change 3 strings in french

- README.md
> docs: add funding information

- .github/workflows/commitlint.yml
This updates the commitlint-action to v5
> ci: update commitlint action to v5

- README.md
This adds a contributors section to the readme.
> docs: add section showing contributors

- renovate.json
> fix: correct the renovate JSON

- src/Component/Renderer/OlRenderer/OlRenderer.tsx
- src/Component/Renderer/Renderer/Renderer.tsx
- src/Component/Renderer/SLDRenderer/SLDRenderer.tsx
- src/context/GeoStylerContext/GeoStylerContext.tsx
This adds the `SLDRenderer` to the `CompositionContext`.
> Add `SLDRenderer` to CompositionContext

- .github/workflows/release.yml
Updates the release token for the semantic release action
> Updates the release token for the semantic release action

- .github/workflows/release.yml
Replaces deprecated script with `npm run build` in release.yml.
> Update "Build artifacts" in release.yml

- package-lock.json
- package.json
- src/Util/FilterUtil.ts
- src/Util/RuleGeneratorUtil.ts
This fixes #2347 by improving a null check to handle `0` correctly.
> fix: fixes rule generation for 0 values

- src/locale/zh_CN.ts
Add translation for Todos, and correct several improper translations.
> Update translation for `zh_CN`

- .github/workflows/on-publish.yml
- .github/workflows/on-push-main.yml
This fixes the pipeline that deploys the documentation to gh-pages which was broken due to breaking changes in the used action.
> ci(gh-pages): adjust pipelines to work with github-pages-deploy-action@4

- .releaserc
This (should) enable beta releases for a branch named 'beta'. This can be useful to create pre-releases that run through the same pipelines as actual releases.
> ci: enable beta releases for branch 'beta'

- .github/workflows/on-publish.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-main.yml
> ci: use npm ci in pipelines

- .github/workflows/notify-discord.yml
- .github/workflows/release.yml
This adds the `Discord notification 📯` action to send a message to the discord server every time the package is released.
> Introduce discord notification action

- index.html
This fixes the devPlayground by updating the preview correctly.
Also adds a bit padding.
Fixes #2406
> Update dev playground

- .github/workflows/notify-discord.yml
This adds a link to the message send to discord.
> Add link to discord message

- src/Component/Filter/FilterTree/FilterTree.example.md
- src/Component/Filter/FilterTree/FilterTree.less
- src/Component/Filter/FilterTree/FilterTree.tsx
- src/Component/FunctionUI/FunctionUI.less
This updates styling of the `FilterTree` and the `FunctionUI`.
> Update styling of `FilterTree` and `FunctionUI`

- src/Component/Symbolizer/Field/ColorField/ColorField.example.md
- src/Component/Symbolizer/Field/ColorField/ColorField.tsx
This fixes the value handling of the `ColorPicker`.
Fixes #2402
> Fixes passed value of `ColorPicker`

- src/Component/FunctionUI/functionConfigs.ts
This adds the missing configs for the remaining uncovered geostyler-style functions.
> Add missing functions to FunctionUI

- .github/workflows/commitlint.yml
- .github/workflows/dev-setup-working.yml
- .github/workflows/on-publish.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-main.yml
- .github/workflows/release.yml
This updates some github actions to their latest versions.
> Update github actions

- package-lock.json
- package.json
This adds a missing dependency for the semantic releases.
> Add missing commit-analyzer

- .github/workflows/release.yml
This upgrades the semantic release action from v4 to v4.1.0.
> ci: bump semantic-release-action

- .github/workflows/release.yml
This uses the `GITHUB_TOKEN` for running the release pipeline as this token should have all needed permissions and will be created automatically. This also commits the changes made in the last step of the release pipeline. The commit was prefixed with `fix` in order to be able to directly check the pipeline.
> fix: use github-actions user for ci tasks

- .github/workflows/release.yml
This removes the invalid `uses` property in the last step of the release workflow.
> fix: remove invalid uses in release workflow step

- .gitignore
- src/Component/CodeEditor/CodeEditor.less
- src/Component/CodeEditor/CodeEditor.tsx
- src/locale/de_DE.ts
- src/locale/en_US.ts
- src/locale/es_ES.ts
- src/locale/fr_FR.ts
- src/locale/hr_HR.ts
- src/locale/locale.ts
- src/locale/zh_CN.ts
> Add upload button (not mandatory)

- .github/workflows/release.yml
This fixes the commitmessage for the automated update of the `README.md`
> Fix commit message for README update

- package-lock.json
- package.json
- src/Component/PreviewMap/PreviewMap.tsx
- src/Component/Renderer/OlRenderer/OlRenderer.tsx
This updates the geostyler-sld-parser to the latest version.
It also updates the dev dependency of ol to the latest version.
> Updates geostyler-sld-parser to v7 and ol to v10 (dev dependency)

- index.html
- vite.dev.config.ts
- bumps the version of antd in the index.html
- adds info about using vite with npm link
> Minor improvements

- src/Component/Symbolizer/FillEditor/FillEditor.tsx
- src/Component/Symbolizer/LineEditor/LineEditor.tsx
- src/locale/de_DE.ts
- src/locale/en_US.ts
- src/locale/es_ES.ts
- src/locale/fr_FR.ts
- src/locale/hr_HR.ts
- src/locale/locale.ts
- src/locale/zh_CN.ts
This adjusts the collapsibles according to the antd deprecation warning.
> refactor: adjust antd Collapse according to deprecation warning

- README.md
> docs: add code sprint 2025 announcement

- README.md
> docs: update code sprint 2025 announcement

- src/Component/ExpressionInput/NumberExpressionInput/NumberExpressionInput.css
- src/Component/ExpressionInput/NumberExpressionInput/NumberExpressionInput.tsx
- src/Component/Symbolizer/Field/OpacityField/OpacityField.tsx
Fix issue [Use a slider for opacity fields #2565]
> feat: opacity field as slider #2565

- src/Component/Filter/FilterTree/FilterTree.tsx
- src/Util/FilterUtil.ts
This does some minor cleanup with some imports.
> Cleanup imports

- src/Component/Filter/FilterEditorWindow/FilterEditorWindow.tsx
- src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.tsx
- src/locale/de_DE.ts
- src/locale/en_US.ts
- src/locale/es_ES.ts
- src/locale/fr_FR.ts
- src/locale/hr_HR.ts
- src/locale/locale.ts
- src/locale/zh_CN.ts
Apply or cancel modifications made in modals #2576
Normally n breaking changes
> apply or cancel modifications made in modals #2576

- src/Component/Symbolizer/Field/ColorField/ColorField.css
- src/Component/Symbolizer/Field/ColorField/ColorField.tsx
Scope the color picker styles to geostyler components so they don't change other usages.
Fixes #2631
> fix(ColorField): Scope color picker styles
