src/Model/Data/Data.spec.ts

This removes an unused import in the unit test spec for the Data model class. Satisfies the upcoming ts-lint configuration introduced by PR #15.

Remove unused import in Data model class test

---

package-lock.json
package.json

Integrates the OpenLayers lib incl. the TS types from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ol
The ``@types/ol`` repo does not support the latest version of OL (v4.6.5). It only supports v4.6.1, but since OL uses semantic versioning I do not expect any problems by using OpenLayers v4.6.5.   
Fixes #83.

Integrate OpenLayers incl. TS types

---

src/Component/Rule/Rule.tsx
src/Component/Symbolizer/Preview/Preview.css
src/Component/Symbolizer/Preview/Preview.spec.tsx
src/Component/Symbolizer/Preview/Preview.tsx

This adds a symbolizer preview realized as OpenLayers map. The preview component expects somes features (GeoJSON) and a symbolizer to define the style of the features on the map. 
Also a predefined OpenLayers map instance or an array of OpenLayers layers can be passed in to customized the setup of the map.

Add OL-map based symbolizer preview

---

.gitignore
package.json
src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Filter/BoolFilterField/BoolFilterField.tsx
src/Component/Filter/OperatorCombo/OperatorCombo.tsx
src/Component/Filter/TextFilterField/TextFilterField.tsx
src/Component/Rule/NameField/NameField.tsx
src/Component/Rule/TitleField/TitleField.tsx
src/Component/ScaleDenominator/MaxScaleDenominator.tsx
src/Component/ScaleDenominator/MinScaleDenominator.tsx
src/index.js
tsconfig.json

This PR enhances build procedure of `geostyler` to enable its usage in other projects (e.g. `react-geo`). 
In particular:
* compliled output (using `tsc`) and CSS files are exposed in `dist` folder by running `npm run build`
* Named exports of each included module (as in `react-geo`)

Compile lib to dist folder

---

package.json
src/Component/FieldSet/FieldSet.spec.tsx
src/Component/Filter/AttributeCombo/AttributeCombo.spec.tsx
src/Component/Filter/BoolFilterField/BoolFilterField.spec.tsx
src/Component/Filter/ComparisonFilter/ComparisonFilter.spec.tsx
src/Component/Filter/NumberFilterField/NumberFilterField.spec.tsx
src/Component/Filter/OperatorCombo/OperatorCombo.spec.tsx
src/Component/Filter/TextFilterField/TextFilterField.spec.tsx
src/Component/Rule/NameField/NameField.spec.tsx
src/Component/Rule/RemoveButton/RemoveButton.spec.tsx
src/Component/Rule/Rule.spec.tsx
src/Component/Rule/TitleField/TitleField.spec.tsx
src/Component/ScaleDenominator/MaxScaleDenominator.spec.tsx
src/Component/ScaleDenominator/MinScaleDenominator.spec.tsx
src/Component/ScaleDenominator/ScaleDenominator.spec.tsx
src/Component/Symbolizer/Preview/Preview.spec.tsx
src/Component/UploadButton/UploadButton.spec.tsx
src/Util/TestUtil.tsx
src/app/Demo/DataProvider/DataProviderUi.spec.tsx
src/app/Demo/FilterUi/FilterDemo.spec.tsx
src/app/Demo/Rule/RuleDemo.spec.tsx
src/setupTests.ts

This adds a util class for useful static unit test helper methods. Herewith ``enzyme`` and the corresponding ``enzyme-react-adapter`` are added as dev-dependency and are setup correctly.
Also adds basic rendering unit tests for the UI components.

Improve test setup and add basic unit tests for UI components 

---

.gitignore
package-lock.json
package.json
src/Component/Rule/Rule.tsx
src/Component/Symbolizer/CircleEditor/CircleEditor.tsx
src/Component/Symbolizer/Editor/Editor.css
src/Component/Symbolizer/Editor/Editor.spec.tsx
src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Field/ColorField/ColorField.css
src/Component/Symbolizer/Field/ColorField/ColorField.tsx
src/Component/Symbolizer/Field/OpacityField/OpacityField.tsx
src/Component/Symbolizer/Field/RadiusField/RadiusField.tsx
src/Component/Symbolizer/Field/WidthField/WidthField.tsx
src/Component/Symbolizer/Preview/Preview.css
src/Component/Symbolizer/Preview/Preview.tsx
src/app/Demo/Rule/RuleDemo.tsx
src/index.js
tslint.json

This introduces a basic Symoblizer Editor. It adds support for editing `CircleSymbolizer`s.
It includes some Field Components which can be reused with other Symbolizer-Editors.
It also adds some minor changes to the RuleDemo.
Closes #74 
Closes #82

 Introduces basic Symbolizer Editor

---

package-lock.json
package.json
src/Component/CodeEditor/CodeEditor.css
src/Component/CodeEditor/CodeEditor.tsx
src/Component/DataInput/DataLoader/DataLoader.tsx
src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Filter/BoolFilterField/BoolFilterField.tsx
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/Filter/NumberFilterField/NumberFilterField.tsx
src/Component/Filter/OperatorCombo/OperatorCombo.tsx
src/Component/Filter/TextFilterField/TextFilterField.tsx
src/Component/Rule/Rule.tsx
src/Component/ScaleDenominator/ScaleDenominator.tsx
src/Component/Style/Style.tsx
src/Component/Symbolizer/CircleEditor/CircleEditor.tsx
src/Component/Symbolizer/Preview/Preview.tsx
src/app/App.css
src/app/App.tsx
src/app/data/TemplateStyle.ts
src/setupTests.ts

This introduces the live CodeEditor.
It displays the current style representation and allows cross side editing of the style.
It includes a Format SelectField which allows the input of GeoStyler Style Parsers to edit the Style in the format you like (how awesome is that? :open_mouth:   ).
**GeoStyler Style:**
**SLD:**
According to testing the bidirectional synchronization some bugs regarding the manipulation of the immutable state object occurred. A fix is included that uses `cloneDeep` before setting new value on state properties.
This also includes a TemplateStyle that is loaded initially.

Introduces the (live) CodeEditor

---

src/index.js

Since `NameField` has been moved to `Component/` sub-folder, the import didn't work properly. This PR fixes this.

Fix erroneous export of NameField

---

src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Filter/BoolFilterField/BoolFilterField.tsx
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/Filter/NumberFilterField/NumberFilterField.tsx
src/Component/Filter/OperatorCombo/OperatorCombo.tsx
src/Component/Filter/TextFilterField/TextFilterField.tsx

This changes the type declaration from any to ``Data`` (``import { Data } from 'geostyler-data'``) for the properties holding the internal data reference.
Fixes #158.

Set correct type for internal data references

---

src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/Filter/OperatorCombo/OperatorCombo.tsx

This filters the available select options in the OperatorCombo due to a changed attribute type.
Fixes #71.

Filter operators due to changed attribute type

---

src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/LineEditor/LineEditor.spec.tsx
src/Component/Symbolizer/LineEditor/LineEditor.tsx
src/Util/TestUtil.tsx

This adds a simple editor for ``LineSymbolizer``s, which allows to edit the 
- color 
- width and
- opacity
of the line.

Add a simple editor for line symbolizer

---

src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Filter/ComparisonFilter/ComparisonFilter.css
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/Filter/NumberFilterField/NumberFilterField.tsx
src/Component/Filter/OperatorCombo/OperatorCombo.tsx
src/Component/Filter/TextFilterField/TextFilterField.tsx

This PR adds form validation to ComparisonFilter GUI and adds some props in order to pass custom placeholder strings to e.g. AttributeCombo (needed esp. for i18n).
`ComparisonFilter` got a new prop `onValidationChanged` (function) that obtains the current validation status of the child elements.
GUI examples:

ComparisonFilter GUI: Form validation and label improvements

---

src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/FillEditor/FillEditor.spec.tsx
src/Component/Symbolizer/FillEditor/FillEditor.tsx
src/Util/TestUtil.tsx

This adds a simple editor for ``FillSymbolizer``s, which allows to edit the
- fill color
- fill opacity and
- stroke color
of the polygon.

Add a simple editor for fill symbolizer 

---

src/Component/FieldSet/FieldSet.tsx
src/Component/Rule/Rule.tsx

This introduces the `onCheckChange` prop for the `FieldSet` and adds corresponding functions for the `Filter` and `ScaleDenominator` `FieldSet`s.
Fixes #175 
Fixes #176

Introduces onCheckChange listeners for FieldSets

---

src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Field/FontPicker/FontPicker.spec.tsx
src/Component/Symbolizer/Field/FontPicker/FontPicker.tsx
src/Component/Symbolizer/Field/OffsetField/OffsetField.spec.tsx
src/Component/Symbolizer/Field/OffsetField/OffsetField.tsx
src/Component/Symbolizer/TextEditor/TextEditor.spec.tsx
src/Component/Symbolizer/TextEditor/TextEditor.tsx
src/Util/TestUtil.tsx

This adds a simple editor for ``TextSymbolizer``s, which allows to edit the
- text color
- font type
- text opacity
- text size
- text offset
of the label / text:

Add a simple editor for text symbolizer

---

src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Field/KindField/KindField.tsx
src/Component/Symbolizer/Preview/Preview.tsx

This Introduces the `KindField` to Select the kind of the `Symbolizer`.
Checks BulletPoint 1 of #160

Introduces the Symbolizer KindField

---

src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Rule/Rule.tsx
src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Preview/Preview.tsx
src/Component/Symbolizer/TextEditor/TextEditor.css
src/Component/Symbolizer/TextEditor/TextEditor.tsx

This adds an `AttributeCombo` component to the `TextEditor` in order to let the user select the field / attribute which is used as label in the map.
Herewith the `SymbolizerPreview` is changed that it accepts the full internal data object (instead of just the features), so the schema can be forwarded to the new `AttributeCombo`.
At the moment the preview only works for string based fields. A separate issue will opened since this could be a problem in the [geostyler-openlayers-parser](https://github.com/terrestris/geostyler-openlayers-parser) .

Add select field for label attribute in TextEditor

---

src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx

This PR introduces a further prop (`boolean`) to hide attribute type in `AttributeCombo`

Hide attribute type in AttributeCombo

---

src/Component/Symbolizer/Editor/Editor.css
src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Field/FontPicker/FontPicker.tsx
src/Component/Symbolizer/Field/ImageField/ImageField.tsx
src/Component/Symbolizer/Field/RotateField/RotateField.tsx
src/Component/Symbolizer/Field/SizeField/SizeField.tsx
src/Component/Symbolizer/IconEditor/IconEditor.tsx
src/Component/Symbolizer/Preview/Preview.tsx
src/app/App.css

This introduces the `IconEditor` to edit `IconSymbolizer`.
It includes some new Fields: `ImageField`, `RotateField`, `SizeField`
It also removes the inline style from the `FontPicker` due to changes in the `Editor.css`.
Closes #160

Introduces IconEditor

---

.vscode/launch.json
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/Filter/TextFilterField/TextFilterField.spec.tsx
src/Component/Filter/TextFilterField/TextFilterField.tsx

This introduces sample values for the `ComparisonFilter`.
When a datasource is imported the standard input field is replaced with an `Autocomplete` field with the (unique) values of the selected Attribute.
The shown options are filtered by the current value. (lowercase & includes)

Introduces sample values for ComparisonFilter

---

src/Component/CodeEditor/CodeEditor.css
src/Component/CodeEditor/CodeEditor.tsx

This PR suggests a UI adaption, so the download button is placed below the CodeEditor. This prevents an ugly line break on smaller screens:
Before:
After:

Set download button below code editor

---

src/Component/DataInput/DataLoader/DataLoader.tsx
src/Component/DataInput/StyleLoader/StyleLoader.tsx
src/app/App.css

This prevents the shift of the select field due to the shown upload button. So the fields keep aligned, even one DataInput shows the upload button and one does not.
Before:
After:

Align DataInput UIs when upload button is shown

---

src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Field/ColorField/ColorField.tsx
src/Component/Symbolizer/Field/FontPicker/FontPicker.tsx
src/Component/Symbolizer/Field/LineDashField/LineDashField.tsx
src/Component/Symbolizer/Field/OffsetField/OffsetField.tsx
src/Component/Symbolizer/Field/OpacityField/OpacityField.tsx
src/Component/Symbolizer/Field/RadiusField/RadiusField.tsx
src/Component/Symbolizer/Field/RotateField/RotateField.tsx
src/Component/Symbolizer/Field/SizeField/SizeField.tsx
src/Component/Symbolizer/Field/WidthField/WidthField.tsx
src/Component/Symbolizer/TextEditor/TextEditor.tsx

This adds some adjustments to the Editor Fields.
1. When selecting a new `SymbolizerKind` a new empty symbolizer while be created.
2. Default values are removed from the Editor Fields to make sure that Preview, Editor and CodeEditor are in sync.
Closes #212

Symbolizer Editor Field adjustments

---

src/Component/Filter/ComparisonFilter/ComparisonFilter.spec.tsx
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx

This adds a default validation function to validate the values of a `ComparisonFilter`. At the moment numeric values are validated whether
- the value type is numeric and
- a numeric value is inside the min/max-range
This reworks the validation function signature to
`value: (value: string | number | boolean| null, internalDataDef?: Data, selectedAttribute?: string) => ValidationResult;`
whereas `ValidationResult` is an object like
```
{
isValid: false,
erorMsg: 'Please enter a number'
}
```
This is a kind of an API break for existing validation functions. Maybe important for @ahennr.

Validate minimum / maximum values in NumberField

---

src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/ScaleDenominator/ScaleDenominator.tsx
src/app/App.css

This optimizes the layout for small screens (phones and tablets in portrait mode). Graphical Editor and Code editor are shown one below the other. Same is done for child elements of `ScaleDenominator` and
`ComparisonFilter` UI.
Before:
After:

Optimize app layout for small screens

---

src/Component/Style/Style.tsx

This sets the key for the Rule UIs to somethings which is not related to the rule's name. Otherwise the Rule UI is re-created every time the user changes the rule name.
Fixes #234.

Replace name as key for Rule UI

---

package.json
src/Component/FieldSet/FieldSet.tsx
tsconfig.json

This updates several pacakges.
It also sets `strictNullChecks:false` option to false in the `tsconfig.`
The option affected the use of `this.state` in many components. And it showed errors that this might be null... even the state was set in the constructor. To avoid this (falsy) warning the option was set to false.
Also `return;` has to be replaced with `return undefined;` :man_facepalming:.
Closes #259 
Closes #258
Closes #257 
Closes #256 
Closes #255
Closes #253 
Closes #252 
Closes #251

Updates packages and disable strictNullChecks

---

package.json

This adds [`--runInBand`](http://jestjs.io/docs/en/cli#runinband) to the test script to avoid tests timing out on Travis CI.

Fixes tests on CI

---

src/Component/CodeEditor/CodeEditor.tsx
src/Component/DataInput/DataLoader/DataLoader.tsx
src/Component/DataInput/StyleLoader/StyleLoader.tsx
src/Component/LocaleWrapper/LocaleWrapper.tsx
src/Component/Rule/Rule.tsx
src/Component/ScaleDenominator/ScaleDenominator.tsx
src/Component/Style/Style.tsx
src/Component/Symbolizer/CircleEditor/CircleEditor.tsx
src/Component/Symbolizer/Field/ColorField/ColorField.tsx
src/Component/Symbolizer/Field/KindField/KindField.tsx
src/Component/Symbolizer/FillEditor/FillEditor.tsx
src/Component/Symbolizer/IconEditor/IconEditor.tsx
src/Component/Symbolizer/LineEditor/LineEditor.tsx
src/Component/Symbolizer/Preview/Preview.tsx
src/Component/Symbolizer/TextEditor/TextEditor.tsx
src/app/App.tsx
src/index.js

localize from LocaleWrapper.ts did not work properly when minified. Due to renaming of class names, localize could not find the matching properties in the language packs. Bug was fixed through adding the original class name of a component as additional parameter in localize.
Every class that is wrapped in localize now has a static property componentName. This property will then be added as parameter to localize.

Fix internationalisation minify bug

---

src/Component/Symbolizer/Field/LineCapField/LineCapField.spec.tsx
src/Component/Symbolizer/Field/LineCapField/LineCapField.tsx
src/Component/Symbolizer/Field/LineJoinField/LineJoinField.spec.tsx
src/Component/Symbolizer/Field/LineJoinField/LineJoinField.tsx
src/Component/Symbolizer/Field/OffsetField/OffsetField.tsx
src/Component/Symbolizer/LineEditor/LineEditor.tsx
src/Component/Symbolizer/Preview/Preview.tsx
src/index.js
src/locale/de_DE.js
src/locale/en_US.js

**Important:** Please wait with merging this PR until 
were merged.
Ui now also handles `lineCap`, `lineJoin` and `lineDashOffset` in LineSymbolizer. `lineDashOffset` field is only active, if a lineDash was specified.
In order to make it running without the PR of types/ol, you can add following lines to `node_modules/@types/openlayers/index.d.ts` (the other three PRs must be merged before, anyway):
line 10144:
```
/**
* Get the line dash offset style for the stroke.
* @return Line dash offset
* @api
*/
getLineDashOffset(): number;
/**
* Set the line dash offset.
*
* @param lineDashOffset Line dash offset.
* @api
*/
setLineDashOffset(lineDashOffset: number): void;
```
line 12366 (`Interface StrokeOptions`):
```
lineDashOffset?: number;
```

Update UI to LineSymbolizer changes

---

src/Component/Style/Style.tsx

IconSymbolizer was missing default value `image`. When adding a new Rule where IconSymbolizer was first symbolizer, an error was thrown. Fixed this through adding defaultIconSource to getSymbolizerFromStyleType, if symbolizer.kind is 'Icon'.

IconSymbolizer fix when adding rule

---

src/Component/Symbolizer/Preview/Preview.css

By setting overflow of Tab to visible, issue of only partially visible colorpickers is resolved.
resolves #333

Fix only partially visible colorpicker

---

src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/Filter/OperatorCombo/OperatorCombo.tsx

This PR adds following props to `OperatorCombo`
* show title of selected item (when selected item hovered) -> `boolean`
* mapping function for operator titles

Mapping function for titles in operator combo and disable titles

---

package.json
public/img/openLayers_logo.svg
src/Component/Style/Style.tsx
src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Field/GraphicTypeField/GraphicTypeField.spec.tsx
src/Component/Symbolizer/Field/GraphicTypeField/GraphicTypeField.tsx
src/Component/Symbolizer/Field/ImageField/ImageField.tsx
src/Component/Symbolizer/GraphicEditor/GraphicEditor.spec.tsx
src/Component/Symbolizer/GraphicEditor/GraphicEditor.tsx
src/Component/Symbolizer/IconEditor/IconEditor.tsx
src/Component/Symbolizer/LineEditor/LineEditor.tsx
src/index.js
src/locale/de_DE.js
src/locale/en_US.js

**Important:** Please wait with merging this PR until
were merged.
With this PR, geostyler can handle graphicFill and graphicStroke of a LineSymbolizer. This should allow defining styles as described in [this issue](https://github.com/terrestris/geostyler/issues/242). So far, two kinds of styles can be added to graphicFill and graphicStroke: wellKnownSymbol or Icon.
New Components for handling graphicFill and graphicStroke were added:
- **GraphicTypeField:** selecting between supported GraphicTypes (so far `Mark` and `Icon`)
- **GraphicEditor:** handling display of fields depending on GraphicTypeField selection (using `MarkEditor` or `IconEditor`)
Options in `GraphicTypeField` can be deselected. The property will then be removed from the style.
To keep the LineSymbolizer UI compact, …

LineSymbolizer GraphicFill and GraphicStroke

---

src/Component/Symbolizer/FillEditor/FillEditor.tsx
src/locale/de_DE.js
src/locale/en_US.js

**Important:** Please wait with merging this PR until
were merged.
With this PR, geostyler can handle graphicFill of a PolygonSymbolizer. This should allow defining styles as described in [this issue](https://github.com/terrestris/geostyler/issues/214). So far, two kinds of styles can be added to graphicFill: wellKnownSymbol or Icon.
To keep the FillEditor UI compact, antd's Collapse component was used to collapse/expand different sections within FillEditor. This is subject of change, with regard to [this comment](https://github.com/terrestris/geostyler/issues/355#issuecomment-414199717).
**Note:** Openlayers API does not natively support graphicFill for Polygons. Thus, geostyler-openlayers-parser was not updated and the Preview does not render changes in graphicFill. However, …

FillSymbolizer GraphicFill

---

src/Component/Symbolizer/Field/GraphicTypeField/GraphicTypeField.tsx
src/Component/Symbolizer/LineEditor/LineEditor.tsx
src/index.js
src/locale/de_DE.js
src/locale/en_US.js

**Important:** Please wait with merging this PR until new version of geostyler-openlayers-parser was released.
graphicTypeField was not exported correctly. instead of pointing to `/Field/GraphicTypeField/GraphicTypeField` it was pointed to `/Field/GraphicField/GraphicField`. 
Multiple other components were not exported in index.js.
Improved i18n translations.
Added graphicTypeField property `clearable`.

Fixes and improvements

---

src/Component/Symbolizer/Preview/Preview.tsx

Additional prop `enableSymbolizerButton` was added to Preview component. Defaults to `true`. If false, the Preview does not show the `Edit Symbolizer` and hence, symbolizers cannot be opened from within the Preview. This is useful for cases where Symbolizers should not be placed within the Preview but at other positions, e.g. above the ScaleDenominator Fieldset.

Add enableSymbolizerButton to Preview Component

---

src/Component/Rule/Rule.tsx

This fthe broken filter / scale checkboxes in the `Rule` UI
closes #434

Fixes broken filter/scale checkboxes

---

package.json
src/Component/Rule/Rule.tsx
src/Component/Style/Style.tsx
src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/EditorWindow/EditorWindow.css
src/Component/Symbolizer/EditorWindow/EditorWindow.tsx
src/Component/Symbolizer/MultiEditor/MultiEditor.css
src/Component/Symbolizer/MultiEditor/MultiEditor.tsx
src/Component/Symbolizer/Preview/Preview.tsx
src/locale/de_DE.js
src/locale/en_US.js

This introduces two new Components:
`MultiEditor` -> Receives multiple symbolizers and creates the needed tabs and buttons.
`EditorWindow` -> Edit symbolizers in a window-like component
@terrestris/devs @chrismayer review appreciated

Introduces the EditorWindow and MultiEditor

---

src/Component/Symbolizer/MarkEditor/MarkEditor.spec.tsx
src/Component/Symbolizer/MarkEditor/MarkEditor.tsx

Styles will not reset anymore when switching between different WellKnownNames. Since all Symbols have the same properties, it does not make sense to do so. -> this PR.
Example: Default Symbolizer with styles
Directly after changing Symbol from `Circle` to `Square`

Keep styles when switching between WellKnownNames

---

.gitignore
.vscode/tasks.json
browser-build.config.js
package.json
src/index.js
tsconfig.json

This PR enables building of a browser library that allows using geostyler outside of the react universe. An existing PR for webpack 4 already exists [here](https://github.com/terrestris/geostyler/pull/413) as well as a corresponding [issue](https://github.com/terrestris/geostyler/issues/419), which will be partially solved through this PR. 
`browser-build.config.js` was created which is a simple webpack config. It was renamed so it is clear that it will only be used for creating the browser version. According script was added to package.json and can be called via `npm run build:browser`. This was also integrated into the `npm run build` script.
Since we are still using webpack 3, `create-react-app-typescript` still runs without errors.
The build output is available in `/browser`.
Also …

Add config for building browser library with webpack 3

---

src/Component/DataInput/StyleLoader/StyleLoader.tsx

The removed line led to adding the whole antd.css to the browser-build css, which overwrote our own styles. Fixed this.

Remove unnecessary antd.css

---

package.json

Greenkeeper tried to install a now reverted version of canvas-prebuilt in #407. I guess because of this, it will not open a new PR with a previous version. Thus, making this PR on my own.

Update canvas-prebuilt to v1.6.11

---

src/Component/Symbolizer/EditorWindow/EditorWindow.css
src/Component/Symbolizer/EditorWindow/EditorWindow.tsx

The drag event on the whole window lead to loosing focus of input fields (related issue here #504). Problem was fixed through limiting the drag event to the EditorWindow Titlebar. Also Cursor style is set to pointer when hovering over Titlebar.

Fix EditorWindow Drag Bug

---

package.json
src/Component/Symbolizer/Preview/Preview.tsx

Version 0.18.0 contains a breaking change. Thus, update had to be done manually.
The returned style(s) of geostyler-openlayers-parser are now directly usable with openlayers. Thus, could remove some logic from `Preview`.

Update geostyler-openlayers-parser to v0.18.0

---

src/Component/Symbolizer/FillEditor/FillEditor.tsx
src/locale/de_DE.js
src/locale/en_US.js

This introduces the editor field for the `outlineWidth` of the `FillSymbolizer`:

Introduces outlineWidth input to FillSymbolizer

---

.vscode/tasks.json
src/Component/LocaleWrapper/LocaleWrapper.tsx
src/Component/Rule/Rule.css
src/Component/Rule/Rule.tsx
src/Component/Style/Style.spec.tsx
src/Component/Style/Style.tsx
src/Component/Symbolizer/EditorWindow/EditorWindow.tsx
src/Component/Symbolizer/MultiEditor/MultiEditor.spec.tsx
src/Component/Symbolizer/MultiEditor/MultiEditor.tsx
src/Component/Symbolizer/Preview/Preview.tsx
src/Component/Symbolizer/Renderer/Renderer.css
src/Component/Symbolizer/Renderer/Renderer.spec.tsx
src/Component/Symbolizer/Renderer/Renderer.tsx
src/app/App.css

This introduces the Symbolizer `Renderer` which is a "lightweight" component to show just one feature with an applied style.
It replaces the `Preview` component in the `Rule`. This leads to further adjustments in other components.

Replace Preview with (new) Renderer Component

---

src/Component/Symbolizer/FillEditor/FillEditor.tsx
src/locale/de_DE.js
src/locale/en_US.js

This adds a `LineDashField` to configure an outline-dasharray for a `FillSymbolizer`.

Introduces OutlineDasharray Field to FillEditor

---

src/Component/LocaleWrapper/LocaleWrapper.tsx
src/Component/Symbolizer/EditorWindow/EditorWindow.tsx

GeoStyler crashed if components were being used without specifying locales. This is now fixed.
Now, if no `LocaleProvider` is specified, `locale` will be set to `undefined` and components use their fallback locales.

Fix localewrapper without locale bug

---

package.json

Since we are using typescript, dependency `prop-types` is not needed. Removed it.

Remove prop-types

---

src/Component/RuleTable/RuleTable.css
src/Component/RuleTable/RuleTable.tsx

This makes the `RuleTable` appearance to be more compact by removing padding and decreasing the size of the `Renderer`.
It also removes the `1:` prefix for scales when the value is empty.

RuleTable enhancements

---

src/Component/RuleTable/RuleTable.tsx
src/Util/FilterUtil.spec.ts
src/Util/FilterUtil.ts

Introduces textual CQL representation of the geostyler-style `Filter`.
For example a geostyler filter of format:
```javascript
[
'&&',
['==', 'state', 'germany'],
[
'||',
['>=', 'population', 100000],
['<', 'population', 200000]
],
[
'!',
['==', 'name', 'Schalke']
]
]
```
becomes
```
'state = germany AND (population >= 100000 OR population < 200000) AND (NOT name = Schalke)'
```
This representation is currently used in the filter field of the `RecordTable`.
We should introduce backwards parsing to allow editing of the `InputField`.

Filter as CQL

---

src/Component/DataInput/DataLoader/DataLoader.tsx
src/Component/DataInput/StyleLoader/StyleLoader.tsx

**Important:** Do not merge this PR until a new version of geostyler-geojson-parser was released (currently version 0.4.5)
Fixes data and style upload loading animation. Before, loading animation did not stop after upload. Now it does. Also handles invalid uploads and shows information on tooltip (see screenshot).
Error message for upload style: _Upload failed. Invalid Style._  
Error message for upload data: _Upload failed. Invalid Data._

Fix loading animation

---

.vscode/tasks.json
src/Component/DataInput/WfsParserInput/WfsParserInput.tsx
src/Component/FieldSet/FieldSet.tsx
src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Filter/BoolFilterField/BoolFilterField.tsx
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/Filter/FilterTree/FilterTree.tsx
src/Component/Filter/NumberFilterField/NumberFilterField.tsx
src/Component/Filter/OperatorCombo/OperatorCombo.tsx
src/Component/Filter/TextFilterField/TextFilterField.tsx
src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Field/FontPicker/FontPicker.tsx
src/Component/Symbolizer/Field/LineCapField/LineCapField.tsx
src/Component/Symbolizer/Field/LineDashField/LineDashField.tsx
src/Component/Symbolizer/Field/LineJoinField/LineJoinField.tsx
src/Component/Symbolizer/GraphicEditor/GraphicEditor.tsx
src/Component/Symbolizer/MarkEditor/MarkEditor.tsx
src/Component/Symbolizer/Renderer/Renderer.tsx
src/Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor.tsx
src/Component/UploadButton/UploadButton.tsx
src/locale/de_DE.js
src/locale/en_US.js

Some components did not update properly since our performance optimizations. Especially switching languages did not work properly, due to some parent components not having locales on their own, and thus, not updating child components. This PR fixes this.
Also added `build:dist` as default task to vscode to run it with `ctrl + shift + b` from within vscode.
Note: FilterTree is still quite slow in comparison to the other components. Relates to #505 
Closes #576

Fix performance related bugs

---

dev-build.config.js

Makes sure the css is also build when using `watch`.

Fix css dev setup

---

src/Component/RuleGenerator/RuleGenerator.tsx
src/Util/RuleGeneratorUtil.spec.ts
src/Util/RuleGeneratorUtil.ts

Setting last bound to max value instead of max value + 1. The generator is already implemented in a way that the last bound is included.
Also removed option`ordinal` since it has no functionality yet and only returns empty rules.

Set last bound to max value

---

src/Component/Rule/Rule.spec.tsx
src/Component/Rule/Rule.tsx
src/Component/Style/Style.tsx
src/Component/Symbolizer/SLDRenderer/SLDRenderer.tsx

Make rule renderer configurable in `Rule.tsx`.
In addition, additional headers for POST request in `SLDRenderer` can be passed (e.g. CSRF token)
Depends on https://github.com/terrestris/geostyler/pull/605
Please review @terrestris/devs

Make rule renderer configurable

---

src/locale/de_DE.js

Title says it all.
Fixes bug in IE11 that doesn't allow duplicate entries in strict mode.

Removes duplicate entry in locale de

---

src/Component/RuleTable/RuleTable.tsx
src/Component/Style/Style.css
src/Component/Style/Style.tsx

Added property `footer` to RuleTable. This passes through a custom footer to antd Table. Removed ButtonGroup below RuleTable and added a Menu into the footer, instead.

Replace ButtonGroup with FooterMenu in RuleTable

---

src/Component/RuleGenerator/RuleGenerator.spec.tsx
src/Component/RuleGenerator/RuleGenerator.tsx

The styler would crash if the user would classify and not choose something in the wellKnownName dropdown.

Set default well known name

---

src/Component/Filter/ComparisonFilter/ComparisonFilter.css

This adds some CSS tweaks to enhance the appearance of `ComparionsFilter`s when using the compact view of a `Style`.

CSS for ComparisonFilter in FilterTree

---

src/Component/RuleTable/RuleTable.tsx

Adding a onHover popover to the filter column of RuleTable to show the whole filter. Text in popover can also be marked and copied. Automatically makes line breaks if content is too long for a single line.

Add popover to show whole filter

---

src/Component/Style/Style.spec.tsx
src/Component/Style/Style.tsx

The multi-edit submenu in the footer of RuleTable will now be disabled if the number of selected rows is `<=1`.
Also, only those menu items of multi-edit are enabled that kann actually be changed for all symbolizers in the current selection. E.g. if a symbolizer of kind 'Line' and a symbolizer of kind 'Mark' are selected, the `size` and `symbol` items are disabled.

Restrict multi-edits in RuleTable

---

src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Filter/NumberFilterField/NumberFilterField.tsx
src/Component/Filter/TextFilterField/TextFilterField.tsx

Preventing drag event on input fileds. This allows the selection of text in input fields within a FilterTree component.

Prevent DragEvent on Filter Inputfields

---

browser-build.config.js
package.json

Since older browsers don't support the `fetch` API, this PR introduces `whatwg-fetch` to browser-build config.
Please review

Use whatwg-fetch for browser builds

---

src/Util/FilterUtil.ts

This fixes the comparison when the filter was parsed (at least) from SLD. In that case all literals will be stored internally as strings, thus previously all comparisons would fail.
This also forces (in-)equality comparisons as strings.
@terrestris/devs @chrismayer Do you have any thoughts on this? IMHO this approach makes the most sense:
* comparing (in-)equality will work perfectly for numbers and strings alike when done as strings
* comparing with `PropertyIsLike` filters makes only really sense in case all operands are strings anyway
* all other comparisons make only sense when using numbers (although the edge case of classifying with the beginning letter might come around some day)

Always compare as float for > and < filters

---

src/Component/Rule/Rule.tsx
src/Component/RuleTable/RuleTable.tsx
src/Component/Style/Style.tsx
src/Component/Symbolizer/BulkEditModals/BulkEditModals.css
src/Component/Symbolizer/BulkEditModals/BulkEditModals.tsx
src/Component/Symbolizer/Editor/Editor.css
src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Field/ImageField/ImageField.css
src/Component/Symbolizer/Field/ImageField/ImageField.tsx
src/Component/Symbolizer/GraphicEditor/GraphicEditor.tsx
src/Component/Symbolizer/IconEditor/IconEditor.tsx
src/Component/Symbolizer/IconSelector/IconSelector.css
src/Component/Symbolizer/IconSelector/IconSelector.spec.tsx
src/Component/Symbolizer/IconSelector/IconSelector.tsx
src/Component/Symbolizer/IconSelectorWindow/IconSelectorWindow.css
src/Component/Symbolizer/IconSelectorWindow/IconSelectorWindow.spec.tsx
src/Component/Symbolizer/IconSelectorWindow/IconSelectorWindow.tsx
src/Component/Symbolizer/MultiEditor/MultiEditor.tsx
src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.tsx
src/Util/TestUtil.tsx
src/index.js
src/locale/de_DE.js
src/locale/en_US.js

Introduces `IconSelectorWindow` and `IconSelector`. Allows selecting icons from multiple libraries. Libraries can be set through `iconLibraries` prop on every relevant component (e.g. `Style`, `IconEditor`, etc.). Type definition of IconLibrary can be found in *src/Components/.../IconSelector.tsx* and looks as follows:
```js
export type IconLibrary = {
name: string;
icons: {
src: string;
caption: string;
}[];
};
```
Example:
```js
var library = [{
name: 'lib 1',
icons: [{
src: 'https://upload.wikimedia.org/.../128px-Parking_icon.svg.png',
caption: 'first image'
}, {
src: 'https://upload.wikimedia.org/.../128px-Parking_icon2.svg.png',
caption: 'second image'
}]
}, {
name: 'lib 2',
icons: [{
src: 'https://upload.wikimedia.org/.../128px-Parking_icon3.svg.png',
caption: 'first image second …
```

Introduce IconSelectorWindow

---

src/Component/RuleTable/RuleTable.css
src/Component/RuleTable/RuleTable.tsx
src/Component/Symbolizer/Renderer/Renderer.css
src/Component/Symbolizer/SLDRenderer/SLDRenderer.css

This deactivates the `duplicates` column in the `RuleTable` as the calculation is currently very inperformant and this is likely to crash the browser.
There are still some further performance issues regarding the `RuleTable` but this one was causing the biggest problems.

Deactivate duplicates column

---

src/Component/CodeEditor/CodeEditor.css
src/Component/CodeEditor/CodeEditor.tsx
src/locale/de_DE.js
src/locale/en_US.js

This adds a "Copy to Clipboard" Button to the `CodeEditor` component coming with a `showCopyButton` property.
`showSaveButton` and `showCopyButton` props are now set to `false` per default.
This also changes the fileending for saved `SLD` files from `[Style.name].xml` to `[Style.name].sld`

Adds "Copy to Clipboard" to CodeEditor

---

src/Component/Symbolizer/BulkEditModals/BulkEditModals.tsx

Instead of the first rule this uses the first selected rule with symbolizers when trying to determine the current style.

Uses the first non-empty rule when multi-editing

---

src/Component/RuleTable/RuleTable.spec.tsx
src/Component/RuleTable/RuleTable.tsx
src/Util/FilterUtil.spec.ts
src/Util/FilterUtil.ts

This now only calculates the amount and duplicates if the data or a filter change. Also, the duplicates detection now uses the results of calculating the matches while determining the count, so the features are only matched once against the filters.

Improves performance of duplicates detection

---

src/Component/Symbolizer/Field/OffsetField/OffsetField.tsx

This removes the `onChange` prop from `OffsetField` props as it is already declared by the partially extended `InputNumberProps` of antd.
This caused an TypeScript-Error when using geostyler.

Removes already declared onChange prop

---

src/Util/FilterUtil.ts

This fixes a bug in duplicates calculation.
As the calculation of duplicates relies on `feature.id` we use the index inside the `FeatureCollection` if the feature has no id.

Adds ids to features if not present

---

.vscode/launch.json
custom.d.ts
package.json
src/Util/HTTPUtil.ts

This fixes the import of `@ungap/url-search-params` polyfill in the `HTTPUtil` which lead to a broken `SLDRenderer`.
Also adapts the launch.json.
Closes #759

Fixes import of URLSearchParams polyfill

---

package.json

This moves @types/react to `devDependencies` and `peerDependencies`.
This is [recommended](https://basarat.gitbooks.io/typescript/content/docs/errors/common-errors.html) and currently leads to issues in the geostyler-demo.
@terrestris/devs please review

Moves @types/react to peerDependencies

---

src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.tsx

Without this, it's possible to move the window partly out of the browser, possibly being stuck without a moving handle.

Constrain the symbolizer window to the body

---

.ci/update-gh-pages.sh

This fixes updating gh-pages when pushing tags.
gh-pages was not updated due to paradox if statements in the script. Previously, we checked if a tag was pushed AND branch is master. Now, we are only checking if a tag was pushed as the travis environment variable `$TRAVIS_BRANCH` equals the tagname when pushing tags. (=> never could be branch `master` AND tag).
The rest of the script was not changed as it should still work properly.

Fix gh-pages (travis-ci.org)

---

src/Component/CodeEditor/CodeEditor.spec.tsx
src/Component/CodeEditor/CodeEditor.tsx
src/Component/DataInput/StyleLoader/StyleLoader.spec.tsx
src/Component/Symbolizer/Editor/Editor.css
src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Field/BrightnessField/BrightnessField.example.md
src/Component/Symbolizer/Field/BrightnessField/BrightnessField.spec.tsx
src/Component/Symbolizer/Field/BrightnessField/BrightnessField.tsx
src/Component/Symbolizer/Field/ColorField/ColorField.tsx
src/Component/Symbolizer/Field/ContrastField/ContrastField.example.md
src/Component/Symbolizer/Field/ContrastField/ContrastField.spec.tsx
src/Component/Symbolizer/Field/ContrastField/ContrastField.tsx
src/Component/Symbolizer/Field/FadeDurationField/FadeDurationField.example.md
src/Component/Symbolizer/Field/FadeDurationField/FadeDurationField.spec.tsx
src/Component/Symbolizer/Field/FadeDurationField/FadeDurationField.tsx
src/Component/Symbolizer/Field/KindField/KindField.tsx
src/Component/Symbolizer/Field/OpacityField/OpacityField.tsx
src/Component/Symbolizer/Field/ResamplingField/ResamplingField.example.md
src/Component/Symbolizer/Field/ResamplingField/ResamplingField.spec.tsx
src/Component/Symbolizer/Field/ResamplingField/ResamplingField.tsx
src/Component/Symbolizer/Field/SaturationField/SaturationField.example.md
src/Component/Symbolizer/Field/SaturationField/SaturationField.spec.tsx
src/Component/Symbolizer/Field/SaturationField/SaturationField.tsx
src/Component/Symbolizer/RasterEditor/RasterEditor.example.md
src/Component/Symbolizer/RasterEditor/RasterEditor.spec.tsx
src/Component/Symbolizer/RasterEditor/RasterEditor.tsx
src/Util/SymbolizerUtil.ts
src/index.ts
src/locale/de_DE.ts
src/locale/en_US.ts

**Important:** Please wait with merging this PR until
was merged and released.
Created UI Components for RasterSymbolizer. Currently, only handles mapbox related properties. Those for SLD will be added in a separate PR.
This is how it looks, if all mapbox related UI Components are included:
However, **only those components are included that comply with the SLD specification**
**Update:** geostyler-mapbox-parser is not necessarily needed. UI Components also work without it. But keep in mind that when parsing to other external formats, information might/will get lost.

Mapbox RasterSymbolizer

---

package.json

Reverts terrestris/geostyler#973
This reverts the major upgrade of np as v5 requires npm >6.8.0 which comes only with node 12 via nvm.
But node 12 seems to conflict with the canvas package.

Revert "Update np to the latest version 🚀"

---

src/Component/RuleTable/RuleTable.tsx
src/Component/Symbolizer/Renderer/Renderer.tsx
src/Component/Symbolizer/SLDRenderer/SLDRenderer.tsx

With this change the internal data gets passed to the `Renderer` so we can preview template strings with curly brackets: e.g:
This also makes the `rasterLayer` prop of the `SLDRenderer` optional.

Add data to Renderer

---

src/Component/Symbolizer/Field/OpacityField/OpacityField.tsx

This adapts the typing of the `onChange` method to the typings of `InputNumberProps` from antd.

Adapts typing for onChange method to antd changes

---

package-lock.json
package.json
webpack.common.config.js

This replaces the deprecated `"browsers"` config in the `autoprefixer` plugin in the `webpack.common.config` with the `"browserslist"` config in the package.json.
This probably fixes #1129

Removes deprecated "browsers" config from webpackconfig

---

src/Component/RuleGenerator/RuleGeneratorWindow.tsx
src/Component/Style/Style.tsx

This fixes the check for `x` and `y` props.
It also sets the `y` position of the `RuleGeneratorWindow` to `0`.

RuleGeneratorWindow position

---

.ci/update-gh-pages.sh

This fixes the detection of Pull Requests in the `update-gh-pages.sh` script and adds some more logs to get a clearer picture why the script stops.
Related to #1134.

1134 gh pages script

---

src/Component/RuleTable/RuleReorderButtons/RuleReorderButtons.spec.tsx
src/Component/RuleTable/RuleReorderButtons/RuleReorderButtons.tsx
src/Component/RuleTable/RuleTable.spec.tsx
src/Component/RuleTable/RuleTable.tsx
src/locale/de_DE.ts
src/locale/en_US.ts
src/locale/es_ES.ts

This introduces two buttons (up / down) in order to allow the user to interactively re-order the rules in the `RuleTable` UI.
Fixes #1141

Add buttons to re-order rules in RuleTable

---

.ci/update-gh-pages.sh

This makes the script run locally when I mockup several of the environment variables of Travis. See e.g. this commit on the `gh_pages`-branch: https://github.com/terrestris/geostyler/commit/1b8ea31c2d48c8d016b6982e5636accd20b63c3a
The docs do not look as if much changed, as we have to list the sections for each component manually… do I understand this correctly? If so, what other otions do we have?
However, the changes herein are separate, and I think these fix the docs autgeneration and publishing.
Please review.

Fix minors in the update-gh-pages script

---

src/Component/Style/Style.spec.tsx
src/Component/Style/Style.tsx
src/locale/de_DE.ts
src/locale/en_US.ts
src/locale/es_ES.ts

This adds a tool to clone existing rules in the `RuleTable`, so users can start new rules based on existing ones.
Closes #1150

Add button to clone a rule in RuleTable

---

.ci/update-gh-pages.sh

This updates the structure of the `gh-pages` resources by:
* Copying the current master version to a folder called `master` containing the latest development resources.
* Copying the current tag to a folder named `v{TAG_VERSION}` and also updates the `latest` folder (which is linked in the gh-pages landing page).

Update folder structure on gh-pages branch

---

.vscode/launch.json
dev-build.config.js
package-lock.json
package.json
transform-less.js
tsconfig.json

This fixes the build by introducing a manual transformation of the `*.less` files.
As typescript does not handle less files a script is needed to do the transformation itself.

Introduces manual '.*less' transformation for dist

---

src/Component/RuleTable/RuleTable.example.md
src/Component/Style/Style.example.md
src/Component/Style/Style.tsx
src/index.ts

Adds examples for `RuleTable` and `Style` components.
Also added `RuleTable` to index.ts since it was missing there.
Relates to #1172 but does not solve it, as many other components are missing examples as well.

Add RuleTable and Style examples

---

package-lock.json
package.json
src/Util/TestUtil.tsx
src/index.ts

antd's `localeProvider` component is deprecated and should be replaced with `configProvider`. This was done in this PR.
- [ConfigProvider docs](https://ant.design/components/config-provider/)
- [deprecated localeProvider docs](https://ant.design/components/locale-provider/)

Replace deprecated localeProvider with ConfigProvider

---

styleguide.config.js

Creates a separate page for each component. This should enhance the readability of the documentation and should motivate writing more detailed documentation and multiple examples of the same component (where appropriate).

Styleguide - Add seperate page for each component 

---

styleguide.config.js

Our documentation should only display our own specified props, not those inherited from antd, etc, since these bloat up the documentation quite heavily and make it difficult to identify the important props.
This PR changes that so only our props will be displayed in the documentation.
Example:
`OpacityField` before (goes on for around 50+ props):
`OpacityField` after:
Code taken from: https://github.com/styleguidist/react-docgen-typescript#parseroptions

Styleguide - Only display non-inherited props

---

src/Component/CompositionContext/CompositionContext.example.md
styleguide.config.js

Adds examples and docs for CompositionContext. Creates an additional `Context` section

Add compositionContext docs

---

package.json

Removes pushing tags as tag creation is done by `np`.  A failing push then causes an unclean release history.

Updates release script

---

src/Component/PreviewMap/PreviewMap.example.md
src/Component/PreviewMap/PreviewMap.less
src/Component/PreviewMap/PreviewMap.spec.tsx
src/Component/PreviewMap/PreviewMap.tsx
src/index.ts

This introduces the `PreviewMap` component.
Which shows the style on a map. The component works without GeoStlyer-Data but it is much more usefull when data is passed:

Introduces PreviewMap component

---

CONTRIBUTING.md

Adds a legalese section to CONTRIBUTING.md to indicate that any contributions will be open source.
Section was adapted from the [actinia project](https://github.com/mundialis/actinia_core/blob/27788176dc05b7b148cad7f10c2ead8add89c40a/CONTRIBUTING.md)

Add Legalese Info To CONTRIBUTING.md

---

README.md

This adds another badge to the readme; this one links to our license. Additionally it also validates that the PR template from #1274 (and later fixed in #1276) works.
This is a follow-up to #1275, this time the PR template actually worked.

Add a license badge

---

.github/pull_request_template.md

This changes some minors in the pull request template:
* the :revolving_hearts:-emoji should now be visible
* extra newline was removed
* explain how to actually check boxes
* add a missing word
Please review.
The already merged PRs #1274 and #1276 are related

Enhance PR template

---

src/Component/Symbolizer/PropTextEditor/PropTextEditor.tsx

See also #1267, the new approach does not use `new RegExp()` and looks
simpler to my eye. Please review. 
Fixes #1267

Simplify formatLine method

---

jest.config.js

This PR suggests to collect overage from the `DataProvider` as well. I think it is fair to assume the current configuration an oversight / bug.
*none*

Collect coverage for ts-files of DataProvider

---

src/Component/Symbolizer/GraphicEditor/GraphicEditor.tsx

This PR just fixes `GraphicEditor` 's attibute `span`, so the component's layout can align with others.
none

GraphicEditor align with other components

---

src/Component/PreviewMap/PreviewMap.tsx

The code for the preview map uses a renamed option for the openlayers geojson format. The option `defaultDataProjection` is now `dataProjection`. See https://openlayers.org/en/v6.4.3/apidoc/module-ol_format_GeoJSON-GeoJSON.html

Use dataProjection in GeoJson Parser

---

src/Component/Symbolizer/Field/ColorField/ColorField.less

In the context of a project I came across the following problem when using GeoStyler:
Color pickers in the "Symbolizer Editor" are not displayed completely, especially if single components of the editor are hidden or in almost any display of the color picker for stroke color settings:
By changing the CSS property of the position the color picker becomes accessible again at least for the user:

Sets color picker to fixed position

---

src/Component/PreviewMap/PreviewMap.example.md
src/Component/PreviewMap/PreviewMap.tsx
styleguide.config.js

This adds the `PreviewMap` component to the docs.
Part of https://github.com/geostyler/geostyler/issues/1172

Add PreviewMap to Docs

---

package-lock.json
package.json
src/Component/DataInput/DataLoader/DataLoader.spec.tsx
src/Component/DataInput/DataLoader/DataLoader.tsx
src/Component/DataInput/StyleLoader/StyleLoader.tsx
src/Component/Filter/FilterTree/FilterTree.tsx
src/Component/Rule/RemoveButton/RemoveButton.tsx
src/Component/Rule/Rule.tsx
src/Component/RuleTable/RuleTable.spec.tsx
src/Component/RuleTable/RuleTable.tsx
src/Component/Style/Style.tsx
src/Component/Symbolizer/ColorMapEditor/ColorMapEditor.spec.tsx
src/Component/Symbolizer/ColorMapEditor/ColorMapEditor.tsx
src/Component/Symbolizer/Field/ChannelSelectionField/ChannelSelectionField.spec.tsx
src/Component/Symbolizer/Field/ChannelSelectionField/ChannelSelectionField.tsx
src/Component/Symbolizer/Field/FontPicker/FontPicker.tsx
src/Component/Symbolizer/Field/ImageField/ImageField.spec.tsx
src/Component/Symbolizer/Field/ImageField/ImageField.tsx
src/Component/Symbolizer/Field/LineDashField/LineDashField.spec.tsx
src/Component/Symbolizer/Field/WellKnownNameField/WellKnownNameField.spec.tsx
src/Component/UploadButton/UploadButton.tsx
tslint.json

This upgrades `antd` to version `4`. It also introduces
- `@ant-design/icons` (replaces `Icon` from antd)
-  `@babel/runtime` (its polyfills are need for the tests)
Related changes to components and tests are needed to fit the new `antd` API.

Upgrade antd to v4

---

src/Component/Filter/FilterEditorWindow/FilterEditorWindow.tsx
src/Component/Rule/RemoveButton/RemoveButton.tsx
src/Component/Rule/Rule.tsx
src/Component/RuleGenerator/RuleGeneratorWindow.tsx
src/Component/RuleTable/RuleReorderButtons/RuleReorderButtons.tsx
src/Component/Style/Style.tsx
src/Component/Symbolizer/Field/LineDashField/LineDashField.tsx
src/Component/Symbolizer/IconSelectorWindow/IconSelectorWindow.tsx
src/Component/Symbolizer/Preview/Preview.tsx
src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.tsx

This PR suggests to pass `Icon` nodes to the `icon` prop of all `Button`s. This is required due to the update of antd to version 4.
See #1327.

Pass icon nodes to the button icon prop

---

src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx

The input fields of the  `ComparisonFilter` have a bug. It is not possible to make edits in the middle or the beginning of the text. After one character is typed, the cursor instantly jumps to the end of the text. See GIF below. The idea was to type "123" in the middle of the text, but the cursor jumps to end after typing the character "1".
I guess the reason for the bug is that the app creates completely new values of the changed input fields. This happens because of the use of `_cloneDeep()`. This causes the app to forget the previous position of the cursor. This Pull Request removes `_cloneDeep()` and re-creates the component state with changed values (not new ones). Afterwords the input works like expected.
Please list issues or pull requests that the changes you propose are related …

Fix Editing in ComparisonFilter

---

src/Component/Filter/FilterTree/FilterTree.less

Fix visibility of minus icon shown inside of filter editor.
The bug could not be observed in [demo](https://geostyler.github.io/geostyler-demo/) and appears only while geostyler UI integration into another application.
The change doesn't affect or breaks current demo, icon is shown as expected furthermore.
Before fix:
After fix: 

Fix visibility of minus icon inside of filter editor

---

src/Component/DataInput/WfsParserInput/WfsParserInput.tsx

Updates the default value for the `WfsParserInput`.
Includes some linting.

Fixes default wfs url for WfsParserInput

---

src/Component/RuleTable/RuleTable.less
src/Component/RuleTable/RuleTable.tsx

This fixes the styling of the `RuleTable` component. It also adds some linting to the `RuleTable` component.
Partially fixes https://github.com/geostyler/geostyler-demo/pull/172

Fixes RuleTable styling

---

src/Component/Symbolizer/MultiEditor/MultiEditor.tsx

Removes `onSymbolizerChange` from `passThroughProps`. Includes some linting.

Removes onSymbolizerChange from passThroughProps

---

src/Component/Symbolizer/FillEditor/FillEditor.spec.tsx
src/Component/Symbolizer/FillEditor/FillEditor.tsx

Fill opacity in FillEditor is invalid, because the property name 'opacity' does not same as geostyler style defination for [FillSymbolizer ](https://github.com/geostyler/geostyler-style/blob/master/index.d.ts#L419). SLD parse implementation only deals with [fillOpacity](https://github.com/geostyler/geostyler-sld-parser/blob/master/src/SldStyleParser.ts#L1527)  field, not  the base property `opacity`.
This PR fix this, so we can get correct SLD from the geostyler style object.
BTW, TextEditor has a `opacity` field too, and geostyler style has no corresponding property, e.g. textOpacity, I'm wondering we may offer a common method for symbolizers  having base property like property. 
Please list issues or pull requests that the changes you propose are related to. It does not matter if they …

fix: Fill opacity cannot transform to sld cssParameter

---

package-lock.json
package.json

This updates `react-styleguidist` to version 11. As this drops node 8 support this also adds the `engines` config to the package.json
This might help https://github.com/geostyler/geostyler/issues/1375. Starts up in less then 5 seconds for me.
- [] Build related changes

Upgrades react styelguide to v11

---

src/Component/DefaultValueContext/DefaultValueContext.tsx
src/Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor.spec.tsx
src/Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor.tsx
src/locale/de_DE.ts
src/locale/en_US.ts
src/locale/es_ES.ts
src/locale/zh_CN.ts

This adds the missing `opacity` field to the `WellKnownNameEditor`.
It is related to https://github.com/geostyler/geostyler/issues/1359.

Adds missing opacity field to WellKnownNameEditor

---

src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/Filter/TextFilterField/TextFilterField.tsx

This fixes the broken comparison filter, so the state reflects the changes in the UI and the dependent components (e.g.) the `CodeEditor` and ensures that the cursor in the attribute- and value-field does not jump to the end while typing. Achieved by doing the following:
This reverts the changeset introduced in #1345, which solved the unwanted cursor jump (see linked PR for details) but also introduced the missing sync of the filter with dependant components e.g. the `CodeEditor` in the GeoStyler-Demo (compare https://github.com/geostyler/geostyler-demo/issues/180).
Additionally an alternative fix for preserving the cursor position and thus allowing to type in the middle of a word in the attribute- and value-field of the comparison filter is now possible. The fix is based on this thread: …

Fix broken comparison filter

---

src/Component/Filter/FilterEditorWindow/FilterEditorWindow.tsx
src/Component/RuleGenerator/RuleGeneratorWindow.tsx
src/Component/Symbolizer/IconSelectorWindow/IconSelectorWindow.tsx
src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.tsx

Previously, it was not possible to close the individual windows via the corresponding button on mobile devices.
With this PR, the focus for the draggable element (`dragHandleClassName`) in the windows (`FilterEditorWindow`, `RuleGeneratorWindow`, `IconSelectorWindow` and `SymbolizerEditorWindow`) is moved from the whole header to the `title`.  
This keeps the components draggable, but also closable on mobile devices.
@jansule @KaiVolland please review

Allows the windows to be closed on mobile devices

---

src/Component/CodeEditor/CodeEditor.example.md
src/Component/PreviewMap/PreviewMap.example.md
src/Component/RuleTable/RuleTable.example.md
src/Component/Style/Style.example.md
src/Component/Symbolizer/Field/WellKnownNameField/WellKnownNameField.example.md
src/Component/Symbolizer/Field/WellKnownNameField/WellKnownNameField.spec.tsx
src/Component/Symbolizer/GraphicEditor/GraphicEditor.example.md
src/Component/Symbolizer/MultiEditor/MultiEditor.spec.tsx
src/Component/Symbolizer/Preview/Preview.spec.tsx
src/Component/Symbolizer/Renderer/Renderer.spec.tsx
src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.spec.tsx
src/Util/FilterUtil.spec.ts

This renames some occurrences of wellKnownName `Circle` to `circle` and `Square` to `square` as this changed in geostylerStyle.
This also adds an example file for the `CodeEditor` component.
None

Circle Fix + CodeEditor Example

---

src/Component/RuleGenerator/RuleGenerator.less
src/Component/RuleGenerator/RuleGenerator.tsx
src/locale/de_DE.ts
src/locale/en_US.ts
src/locale/es_ES.ts
src/locale/zh_CN.ts

This adds a button which set the number of classes in the `RuleGenerator` to the amount of distinct values for the selected attribute.

Introduces "all-distinct-values" button to RuleGenerator

---

src/Component/Style/Style.tsx

This introduces `ruleTableProps` to the `Style` component to allow passing of properties to the antd `Table` component which is used in compact mode.

Introduces ruleTableProps to Style component

---

src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Filter/BoolFilterField/BoolFilterField.tsx
src/Component/Filter/ComparisonFilter/ComparisonFilter.less
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/Filter/FilterTree/FilterTree.less
src/Component/Filter/FilterTree/FilterTree.tsx
src/Component/Filter/NumberFilterField/NumberFilterField.tsx
src/Component/Filter/OperatorCombo/OperatorCombo.tsx
src/Component/Filter/TextFilterField/TextFilterField.tsx

This fixes the layout of the `FilterTree` which was kind of broken (field height, margins, …) due to several antd updates.
It also simplifies the code of the `FilterTree`.
The menu (add, change, remove) is now accesible via a button which is alwas visible.
Before:
After:

Fixes FilterTree layout

---

src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/Filter/ComparisonFilter/ComparisonFilter.less
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx
src/Component/Filter/FilterTree/FilterTree.tsx
src/Component/Filter/NumberFilterField/NumberFilterField.tsx
src/Component/Filter/OperatorCombo/OperatorCombo.tsx
src/Component/Filter/TextFilterField/TextFilterField.less
src/Component/Filter/TextFilterField/TextFilterField.tsx

This adds support for the `IsBetweenOperator` to the `ComparisonFilter`.
It also removes some inline styling and catches undefined `onFilterChange` in the `FilterTree`.
https://github.com/geostyler/geostyler/pull/1556#discussion_r810996640
- [] Code style update (formatting, renaming)

Comparison filter refactoring

---

src/Component/CodeEditor/CodeEditor.tsx

This prevents the code editor breaking the style if invalid text is inserted. Instead, the parse errors are shown in the editor so the user can fix the style.

Allow editing even if document is temporarily invalid

---

package-lock.json
package.json

Updates `react` and `react-dom` to version 17 in the devDependencies.
It also widens the peerDependency range to allow version 16 or later.
This addresses #1524

Update react, react-dom to v17

---

src/Component/Filter/FilterTree/FilterTree.tsx
src/Util/FilterUtil.spec.ts
src/Util/FilterUtil.ts

When using drag'n'drop to change the filter order, dropping filters in lists with more than three filters, dropping a filter on the last ones will lead to the dropped filter being deleted.
This fixes that bug, though drag'n'drop still feels a bit flaky and should be looked at again.

Fix vanishing filters when dropping

---

src/Component/Filter/FilterTree/FilterTree.tsx
src/Component/Style/Style.tsx

This transforms the children of the antd Menus to `items` as the approach of using children is deprecated in the newer antd versions
Closes #1645

Transfer antd menu children to items

---

.github/workflows/on-publish.yml
.github/workflows/on-push-master.yml
README.md

This PR suggests to update the README and use two [worflow status badges from GitHub](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge), and not the non-functional travis one.
none

Include action badges in README

---

src/Component/CardStyle/CardStyle.tsx

This fixes the broken state handling in the card layout breadcrumbs when changing the rule name.
None

Style cards rulename state fix

---

webpack.dev.config.js

Uses `path` module to make styleguidist build work in both linux and windows environments.
refs issue #1726

makes styleguidist config work on windows (refs #1726)

---

jest.config.js

This change in the testMatch expression for jest makes the tests pass in both linux and windows environment.
The previous expression did not match any test on windows.
Issue #1726

change testMatch expression (closes #1726)

---

.github/workflows/on-publish.yml
.github/workflows/on-push-master.yml

This fixes the workflow the deploys the documentation to gh-pages. Previously, the latest build were placed into a directory called `docs` which we did not use before.

Fix documentation workflows

---

styleguide.config.js
webpack.browser.config.js
webpack.dev.config.js

After fiddling around with the current configuration, it looks like the `react-docgen-typescript` is slowing down the initial build of the styleguidist tremendously while checking the props/types of any parent component (e.g. the extended antd types).
This suggests to skip this check in `development` mode which will result in decent startup times (before: ~180s. after: ~20 s), **BUT** the list of props might not be complete. There seems to be a bug while detecting the props of function components as well, see [here](https://github.com/styleguidist/react-styleguidist/issues/1989).
#1375.

Speed up start of the styleguidist

---

.github/pull_request_template.md
.github/workflows/on-push-main.yml
CONTRIBUTING.md
README.md
docs/README.md
package.json

This suggests to adjust several links to the updated name of the default branch.
--

Rename default branch to main

---

src/Component/CardStyle/CardStyle.less
src/Component/CardStyle/CardStyle.tsx
src/Component/RuleFieldContainer/RuleFieldContainer.less

This adds `<Renderer />` to SYMBOLIZERVIEW to enable users to directly see the changes they are applying.
This also changes the cursor to `default` for the non-clickable `<Renderer />`s.
Please note that a proper styling will be part of a subsequent PR, where also the Editor styling will be changed.
https://github.com/geostyler/geostyler/issues/1748

Add Renderer component to SYMBOLIZERVIEW

---

src/Component/PreviewMap/PreviewMap.spec.tsx
src/Component/PreviewMap/PreviewMap.tsx
src/Util/GeometryUtil.ts

This refactors the `Previewmap` component.
1. It transforms it to a React function component.
2. It removes all OlMap specific properties. :exclamation: Breaking Change :exclamation: 
3. Default interactions are active for the `PreviewMap`  :exclamation: Breaking Change :exclamation: 
If you want to configure specific `layer`, `controls`, `interactions` … for the map. Please create the map outside of the component and pass it in.

Refactor `PreviewMap`

---

.github/workflows/dev-setup-working.yml

This PR suggests to add a new workflow that can be [manually triggered from the GitHub website](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow). It tries to execute some steps a developer would usually run, and we verify these all give expected results (i.e. do not err).
In order to test this / execute this, I think it first must be merged:
> To trigger the workflow_dispatch event, your workflow must be in the default branch.
This workflow runs on Windows, macOS and Ubuntu, and ensures that developers with different OS still can work on GeoStyler.
This came up for some devs during the latest Codesprint.

Verify that dev setup works on various OS

---

README.md

This updates the Developer Guide section of the README.md. 
Some configurations in the `geostyler-demo` have changed due to the removal of react-scripts https://github.com/geostyler/geostyler-demo/pull/326.
@slafayIGN please have a look. Lets see if this works for you on windows, too.
This addresses #1769.

updates Developer Guide in README.md

---

src/Component/Renderer/Renderer.example.css
src/Component/Renderer/Renderer.example.md
src/Component/RuleCard/RuleCard.example.md
src/Component/RuleOverview/RuleOverview.example.md
src/Component/Rules/Rules.example.md
src/Component/StyleOverview/StyleOverview.example.md
src/Component/Symbolizer/Editor/Editor.example.md
src/Component/Symbolizer/MarkEditor/MarkEditor.example.md
src/Component/Symbolizer/Preview/Preview.example.md
src/Component/Symbolizer/Renderer/Renderer.example.md
src/Component/Symbolizer/SLDRenderer/SLDRenderer.example.md
src/Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor.example.md
src/Component/SymbolizerCard/SymbolizerCard.example.md
src/Component/Symbolizers/Symbolizers.example.md

This fixes the examples that use symbolizer with wellKnownName. They now all use lowercase.
Also fixes the Renderer example.
Fixes #1832 
- [] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)

Fix examples

---

src/Component/PreviewMap/PreviewMap.tsx

This fixes the typing of the `mapHeight` property in the `PreviewMap`.
It was typed as `number` but actualy accepts all values the CSS height property accepts. Just like '100%', '100vh', …

Fix typing of mapHeight prop in PreviewMap

---

src/Component/Symbolizer/Field/BrightnessField/BrightnessField.tsx
src/Component/Symbolizer/Field/ContrastField/ContrastField.tsx
src/Component/Symbolizer/Field/FadeDurationField/FadeDurationField.tsx
src/Component/Symbolizer/Field/GammaField/GammaField.tsx
src/Component/Symbolizer/Field/OffsetField/OffsetField.tsx
src/Component/Symbolizer/Field/OpacityField/OpacityField.tsx
src/Component/Symbolizer/Field/RadiusField/RadiusField.tsx
src/Component/Symbolizer/Field/RotateField/RotateField.tsx
src/Component/Symbolizer/Field/SaturationField/SaturationField.tsx
src/Component/Symbolizer/Field/SizeField/SizeField.tsx
src/Component/Symbolizer/Field/WidthField/WidthField.tsx
src/Component/Symbolizer/FillEditor/FillEditor.tsx
src/Util/FieldUtil.spec.ts
src/Util/FieldUtil.ts
src/context/DefaultValueContext/DefaultValueContext.example.md

This introduces the `FileUtil.nullToUndefined` modificator. It is used to wrap the `onChange` listeners of the `InputNumberFields`.
Why is this introduced?
Previously when deleting the content of an inputfield the `onChange` listener was called with `null`. In the following a style with `null` was generated instead of removing the unused / resettet property from the style.
As this changes the signature of the properties this is a **BREAKING CHANGE** :exclamation:

Introduces `nullToUndefined` modificator

---

.commitlintrc.json
src/Component/Symbolizer/FillEditor/FillEditor.tsx
src/Component/Symbolizer/IconEditor/IconEditor.tsx
src/Component/Symbolizer/LineEditor/LineEditor.tsx
src/Component/Symbolizer/MarkEditor/MarkEditor.tsx
src/Component/Symbolizer/RasterEditor/RasterEditor.spec.tsx
src/Component/Symbolizer/RasterEditor/RasterEditor.tsx
src/Component/Symbolizer/TextEditor/TextEditor.tsx
src/Util/UnsupportedPropertiesUtil.ts
src/context/UnsupportedPropertiesContext/UnsupportedPropertiesContext.example.md
src/context/UnsupportedPropertiesContext/UnsupportedPropertiesContext.tsx
src/index.ts
src/locale/de_DE.ts
src/locale/en_US.ts
src/locale/es_ES.ts
src/locale/fr_FR.ts
src/locale/locale.ts
src/locale/zh_CN.ts
styleguide.config.js

This introduces the `UnsupportedPropertiesContext`, `UnsupportedPropertiesUtil` and makes use of them in the Symbolizer Editors.
Supported Editors:
- [] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)

Introduces UnsupportedPropertiesContext, Utill and use it in Symbolizer Editors

---

src/Component/DataInput/DataLoader/DataLoader.example.md
src/Component/DataInput/DataLoader/DataLoader.tsx
src/Component/DataInput/StyleLoader/StyleLoader.example.md
src/Component/DataInput/StyleLoader/StyleLoader.tsx
styleguide.config.js

This fixes the never ending loading icon for the UploadButtons in the `DataLoader` and `StyleLoader`. 
It also adds examples for the two components.
#1867

Upload feedback

---

src/Component/PreviewMap/PreviewMap.tsx

Zoom to data if provided to `PreviewMap`.
Fixes #1870

Zoom to data if provided

---

src/Component/RuleFieldContainer/RuleFieldContainer.less
src/Component/RuleFieldContainer/RuleFieldContainer.tsx
src/Component/ScaleDenominator/MaxScaleDenominator.tsx
src/Component/ScaleDenominator/MinScaleDenominator.tsx
src/Component/Symbolizer/TextEditor/TextEditor.tsx
src/index.ts

- adds `CardStyle` to index.ts
- fixes some minor layout bugs regarding the width of a few input fields
--

Layout fixes and missing import

---

src/Component/Symbolizer/TextEditor/TextEditor.example.md
src/Component/Symbolizer/TextEditor/TextEditor.tsx

This closes the curly braces (`}}`) after selecting attributes from the dropdown in the text templating input field, in order to have a proper placeholder string.
--

fix: close curly braces on template attributes

---

src/Component/CodeEditor/CodeEditor.tsx

This fixes the change handling of the `CodeEditor`.
1. Actual call of `onStyleChange` was readded to parser related codeblock.
2. OnChange loop was fixed by using `useRef` for the timeout.

Fix CodeEditor

---

package.json

This extends the version range for ol in the peerDependencies to allow the use of ol 7.

Extend version range to allow ol >=6

---

src/Component/Symbolizer/Field/ColorField/ColorField.less
src/Component/Symbolizer/Field/ColorField/ColorField.tsx
src/locale/de_DE.ts
src/locale/en_US.ts
src/locale/es_ES.ts
src/locale/fr_FR.ts
src/locale/locale.ts
src/locale/zh_CN.ts

This adds a clear button to the color field, which appears when the color picker is visible. Clicking it will unset the color.

feat: add clear button to color field

---

src/Component/Filter/TextFilterField/TextFilterField.tsx

This adds a check to ensure that a variable is actually a string, before using `.toLowerCase()` in `<TextFilterField />`. Before, it was possible to crash geostyler when adding a value to a numeric filter and then switching to a text filter. This at least happens with antd@4.9, whereas the problem could not be reproduced with antd@4.24.2.
--

fix: add check for string before using .toLowerCase() in TextFilterField

---

src/Component/DataInput/WfsParserInput/WfsParserInput.tsx
src/Component/PreviewMap/PreviewMap.tsx
src/locale/de_DE.ts
src/locale/en_US.ts
src/locale/es_ES.ts
src/locale/fr_FR.ts
src/locale/locale.ts
src/locale/zh_CN.ts

This adds a form field to enter the `srsName` for the WFS request to the WfsParserInput.
It also fixes a bug in the `PreviewMap` which causes an application crash.
Fixes https://github.com/geostyler/geostyler-demo/issues/403

Introduces srsName input to `WfsParserInput`

---

src/Component/Filter/ComparisonFilter/ComparisonFilter.example.md
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx

Fix `onValueChange` handler for between compartor in `ComparisonFilter`.
Also adds an example for the `ComparisonFilter`.
Fixes #1970 

Fix onValueChange for ComparisonFilter (between)

---

src/Component/RuleGenerator/ColorRampCombo/ColorRampCombo.example.md
src/Component/RuleGenerator/ColorRampCombo/ColorRampCombo.less
src/index.ts

This fixes the styling of the `ColorRampCombo` by adding an additional selector to hide the default background.
It also adds an example for this component and adds it to the exports of the index.ts.
Fixes #1969 

ColorRampCombo style

---

src/Component/DataInput/DataLoader/DataLoader.tsx
src/Component/UploadButton/UploadButton.tsx

This adds the `uploadButtonProps` property to the `DataLoader`. This way you can pass properties to the used `UploadButton`.
e.g. Its now possible to add a callback to remove the data from the geostlyler after removing an uploaded geojson in the Demo
https://github.com/geostyler/geostyler-demo/issues/405

Introduces uploadButtonProps to DataLoader

---

src/Component/CardStyle/CardStyle.tsx

Removed props `ruleGeneratorProps` and replaced it with props `colorRamps`, `useBrewerColorRamps` and `colorSpaces` in order to harmonize `<CardStyle />` with `<Style />`.
This PR is opened against branch `harmonization` since this is part of a bigger series of related PRs.
https://github.com/geostyler/geostyler-demo/issues/406

CardStyle harmonization

---

src/Component/RuleCard/RuleCard.example.md
src/Component/RuleCard/RuleCard.tsx
src/Component/Rules/Rules.tsx

Removes props `filterUiProps`, `iconLibraries`, `colorRamps` from `<Rules />`. Moves `showAmount`, `showDuplicates` to `<RuleCard />` and to `ruleCardProps` on `<Rules />`.
https://github.com/geostyler/geostyler-demo/issues/406

breaking: remove unnecessary props from Rules

---

src/Component/Symbolizer/IconEditor/IconEditor.spec.tsx
src/Component/Symbolizer/IconEditor/IconEditor.tsx
src/Component/Symbolizer/LineEditor/LineEditor.spec.tsx
src/Component/Symbolizer/LineEditor/LineEditor.tsx
src/Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor.spec.tsx
src/Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor.tsx
src/context/DefaultValueContext/DefaultValueContext.tsx
src/locale/de_DE.ts
src/locale/en_US.ts
src/locale/es_ES.ts
src/locale/fr_FR.ts
src/locale/locale.ts
src/locale/zh_CN.ts

This adds the missing input fields for offset:
- `LineSymbolizer.perpendicularOffset` to `LineEditor`
- `IconSymbolizer.offset` to `IconEditor`
- `MarkSymbolizer.offset` to `WellKnownNameEditor`
Fixes #1495 

Add missing offset fields to symbolizer editors

---

.github/workflows/stale.yml

This introduces the `exempt-issue-labels` and `exempt-pr-labels` configs to the stale.yml.
With this PR it is possible to keep issues or PRs permanently. Just add the "permanent" label.

Add exempt labels config to stale.yml

---

styleguide.config.js

This provides the version of GeoStyler in the docs. Version will be derived from `package.json`.
Please note that this will display the latest version for the `master` docs.
solves https://github.com/geostyler/geostyler/issues/1759

Provide GeoStyler Version in Docs

---

docs/introduction.md

This sets the `max-width` style property for the GeoStyler banner in the docs.
Desktop
Mobile
Please list issues or pull requests that the changes you propose are related to. It does not matter if they are still open and/or unmerged, any link is appreciated.

docs: set max-width of banner

---

src/Component/Filter/FilterTree/FilterTree.tsx

This expands all nodes in the FilterTree by default. It also removes the handling of expanded nodes as it is already done by antd.
This PR also adds the possibilty to pass props to the underlying antd Tree.
Fixes #1979 

Expand FilterTree by default and add posibility to pass TreeProps

---

src/Component/RuleOverview/RuleOverview.tsx
src/Component/StyleOverview/StyleOverview.tsx

This removes the internal state handling for the `StyleOverview` and `RuleOverview` components. This should fix the issue, that these components don't get rerendered when the style is change outside of the `CardStyle` component. E.g. When editing in the CodeEditor in the demo.

Remove internal state handling for CardStyle

---

src/Component/CardStyle/CardStyle.tsx
src/Component/RuleGenerator/ClassificationCombo/ClassificationCombo.less
src/Component/RuleGenerator/ClassificationCombo/ClassificationCombo.tsx
src/Component/RuleGenerator/RuleGenerator.example.md
src/Component/RuleGenerator/RuleGenerator.tsx
src/Component/RuleGenerator/RuleGeneratorWindow.tsx
src/Component/Rules/Rules.tsx
src/Component/Style/Style.tsx
src/Util/RuleGeneratorUtil.ts

This replaces the use of lodash `get` with the corresponding TypeScript syntax in the `RuleGeneratorUtil`.
It also fixes the typing of the `internalDataDef` for the `RuleGenerator`.
It also extends the example for the `RuleGenerator` and adds a minor styling improvement to the `ClassificationCombo`.
This fixe #2012 

Make RuleGeneratorUtil less prone to errors

---

.github/pull_request_template.md

This reduces the pull request template to what is needed. This hopefully reduces the barrier to open a PR and speeds up the process for experienced Github users.

Reduce pull request template

---

src/Component/Symbolizer/Field/OpacityField/OpacityField.tsx
src/Component/Symbolizer/Field/WidthField/WidthField.tsx
src/Component/Symbolizer/FillEditor/FillEditor.example.md
src/Component/Symbolizer/FillEditor/FillEditor.tsx
src/context/GeoStylerContext/GeoStylerContext.tsx

This introduces the usage of GeoStylerContext for default values and composition in the `<FillEditor>`.
BREAKING CHANGE: This removes the support of the deprecated CompositionContext in favor of the new GeoStylerContext for the FillEditor. This also removes the `defaultValues` property from FillEditor. Please use GeoStylerContext.composition instead.

feat: use GeoStylerContext composition on FillEditor.

---

src/Component/Symbolizer/Field/OffsetField/OffsetField.tsx
src/Component/Symbolizer/Field/RotateField/RotateField.tsx
src/Component/Symbolizer/IconEditor/IconEditor.example.md
src/Component/Symbolizer/IconEditor/IconEditor.tsx
src/context/GeoStylerContext/GeoStylerContext.tsx

This makes use of the GeoStylerContext.composition in `<IconEditor>`.
BREAKING CHANGE: This removes the support of the deprecated CompositionContext in favor of the new GeoStylerContext for the IconEditor. This also removes the `defaultValues` property from IconEditor. Please use GeoStylerContext.composition instead.

feat: use GeoStylerContext composition on IconEditor

---

src/Component/Symbolizer/LineEditor/LineEditor.example.md
src/Component/Symbolizer/LineEditor/LineEditor.tsx
src/context/GeoStylerContext/GeoStylerContext.tsx

This makes use of the GeoStylerContext.composition in `LineEditor`.
BREAKING CHANGE: This removes the support of the deprecated CompositionContext in favor of the new GeoStylerContext for the LineEditor. This also removes the `defaultValue` property from LineEditor. Please use GeoStylerContext.composition instead. For now, composition of graphicFill and graphicStroke was changed without replacement. Support will be re-added again in the future.

feat: use GeoStylerContext composition on LineEditor

---

src/Component/Symbolizer/MarkEditor/MarkEditor.example.md
src/Component/Symbolizer/MarkEditor/MarkEditor.tsx
src/context/GeoStylerContext/GeoStylerContext.tsx

This makes use of the `GeoStylerContext` in `MarkEditor`. Handling of the `WellKnownNameEditor` will be part of a subsequent PR.
BREAKING CHANGE: This removes the support for the deprecated CompositionContext in favor of the new GeoStylerContext for the MarkEditor. This also removes the `defaultValues` property from MarkEditor.

feat: use GeoStylerContext composition for MarkEditor

---

src/Component/Symbolizer/Field/RadiusField/RadiusField.tsx
src/Component/Symbolizer/FillEditor/FillEditor.example.md
src/Component/Symbolizer/IconEditor/IconEditor.example.md
src/Component/Symbolizer/LineEditor/LineEditor.example.md
src/Component/Symbolizer/MarkEditor/MarkEditor.example.md
src/Component/Symbolizer/MarkEditor/MarkEditor.tsx
src/Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor.example.md
src/Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor.tsx

This makes use of the `GeoStylerContext` in the `<WellKnownNameEditor>`.
BREAKING CHANGE: This removes the support for the deprecated CompositionContext in favor of the new GeoStylerContext for the WellKnownNameEditor. This also removes the `defaultValues` property for the WellKnownNameEditor. Please use GeoStylerContext.composition instead.

feat: use GeoStylerContext composition for WellKnownNameEditor

---

src/Component/Symbolizer/TextEditor/TextEditor.example.md
src/Component/Symbolizer/TextEditor/TextEditor.tsx
src/context/GeoStylerContext/GeoStylerContext.tsx

This makes use of the `GeoStylerContext` for the `<TextEditor>`.
BREAKING CHANGE: This removes the support for the deprecated CompositionContext in favor of the new GeoStylerContext for the TextEditor. This also removes the `defaultValues` property for the TextEditor. Please use GeoStylerContext.composition instead.

feat: use GeoStylerContext composition for TextEditor

---

src/Component/Symbolizer/Field/ChannelField/ChannelField.tsx
src/Component/Symbolizer/RasterChannelEditor/RasterChannelEditor.tsx
src/Component/Symbolizer/RasterEditor/RasterEditor.example.md
src/Component/Symbolizer/RasterEditor/RasterEditor.tsx
src/context/GeoStylerContext/GeoStylerContext.tsx

This makes use of `GeoStylerContext` for the `<RasterChannelEditor>`.
BREAKING CHANGE: This removes the `defaultValues` property from RasterEditor. Please use GeoStylerContext.composition instead.

feat: use GeoStylerContext composition for RasterChannelEditor

---

src/Component/Filter/ComparisonFilter/ComparisonFilter.example.md
src/Component/Filter/ComparisonFilter/ComparisonFilter.tsx

This makes use of the `GeoStylerContext` in the `<ComparisonFilter>`.

feat: use GeoStylerContext composition for ComparisonFilter

---

src/Component/RuleTable/RuleTable.example.md
src/Component/RuleTable/RuleTable.tsx
src/Component/Rules/Rules.tsx
src/Component/Style/Style.tsx
src/context/GeoStylerContext/GeoStylerContext.tsx

This makes use of the `GeoStylerContext` in `<Rules>` and `<RuleTable>`.
BREAKING CHANGE: This removes the properties `showAmountColumn` and `showDuplicatesColumn` from <RuleTable> and thereby also from <Style>. Please use GeoStylerContext.composition.Rule.amount.visibility and GeoStylerContext.composition.Rule.duplicate.visibility instead.

feat: use GeoStylerContext composition for Rules and RuleTable

---

src/Component/RuleCard/RuleCard.example.md
src/Component/RuleCard/RuleCard.tsx
src/Component/RuleFieldContainer/RuleFieldContainer.tsx
src/Component/RuleOverview/RuleOverview.example.md
src/Component/RuleOverview/RuleOverview.tsx

This makes use of the `GeoStylerContext` for `<RuleCard>` and `<RuleOverview>`.
BREAKING CHANGE: This removes the properties `showAmount` and `showDuplicates` from RuleCard. Please use
GeoStylerContext.composition.Rule.amount and
GeoStylerContext.composition.Rule.duplicate instead.

feat: use GeoStylerContext composition for RuleCard and RuleOverview

---

package-lock.json
package.json
src/Component/Filter/ComparisonFilter/ComparisonFilter.less
src/Component/Filter/FilterEditorWindow/FilterEditorWindow.less
src/Component/Filter/FilterEditorWindow/FilterEditorWindow.tsx
src/Component/Filter/FilterTree/FilterTree.less
src/Component/Rule/Rule.tsx
src/Component/RuleGenerator/RuleGeneratorWindow.less
src/Component/RuleGenerator/RuleGeneratorWindow.tsx
src/Component/RuleTable/RuleTable.tsx
src/Component/Style/Style.tsx
src/Component/Symbolizer/Field/ColorField/ColorField.less
src/Component/Symbolizer/Field/ImageField/ImageField.tsx
src/Component/Symbolizer/IconSelectorWindow/IconSelectorWindow.less
src/Component/Symbolizer/IconSelectorWindow/IconSelectorWindow.tsx
src/Component/Symbolizer/MultiEditor/MultiEditor.tsx
src/Component/Symbolizer/Preview/Preview.tsx
src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.less
src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.tsx

This replaces all `react-rnd` window components with [antd Modals](https://ant.design/components/modal).
Please review.

Replace react-rnd windows with modals

---

src/Component/Symbolizer/Editor/Editor.example.md
src/Component/Symbolizer/Editor/Editor.tsx

This makes use of the `GeoStylerContext` for `<Editor>`.
BREAKING CHANGE: This removes the deprecated CompositionContext in favor of the new GeoStylerContext composition from Editor. This also removes the properties `iconLibraries` and `colorRamps` from Editor. Please use GeoStylerContext.composition.IconEditor.iconLibraries instead. The property `colorRamps` currently has no replacement but this will be re-added soon.

feat: use GeoStylerContext composition for Editor

---

src/Component/Rule/Rule.spec.tsx
src/Component/Symbolizer/MultiEditor/MultiEditor.spec.tsx
src/Component/Symbolizer/MultiEditor/MultiEditor.tsx

This removes the `remove` button from a symbolizer and uses removable tabs instead. Also, the `add` button was replaced with a `+` tab.
closes https://github.com/geostyler/geostyler/issues/2149

feat: replace remove symbolizer button with removable tabs

---

package-lock.json
package.json

This moves the packages `@types/react` and `@types/react-dom` from dependencies to peerDependencies.

build: move @types/react* to peerDependencies

---

.github/workflows/dev-setup-working.yml
.github/workflows/on-pull-request.yml

This PR updates the versions of Node.js used during CI runs.

Use Node.js versions 18.x and 20.x for workflows

---

package-lock.json
package.json
src/Component/PreviewMap/PreviewMap.example.md
src/Component/PreviewMap/PreviewMap.tsx

This enhances the `PreviewMap` example with some sample data. The sample data is in projection "EPSG:3857" to demonstrate the use of `data`  and `dataProjection`.
Closes #2202

Add support for unregistered projections to PreviewMap

---

src/Component/Symbolizer/FillEditor/FillEditor.example.md
src/locale/en_US.ts

This updates the en_US label for the `outlineOpacity` field. It also updates the label for the switch in the example.

Update outline opacity label for en_US

---

renovate.json

This adds `lockFileMaintenance` for the renovate bot.
https://docs.renovatebot.com/key-concepts/automerge/#automerge-lock-file-maintenance

Add `lockFileMaintenance`

---

package.json

This fixes the `prebulishOnly` script by replacing the removed `npm run build-dist` with `npm run build`.

Fix `prepublishOnly` script

---

src/Component/Renderer/OlRenderer/OlRenderer.tsx
src/Component/RuleTable/RuleTable.example.md
src/Component/RuleTable/RuleTable.tsx
src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.example.md

This fixes a strange behaviour when using a geostyler function in a symbolizer property with the `RuleTable` component. The source of this behaviour was this bug: https://github.com/geostyler/geostyler-openlayers-parser/issues/740
To make sure the parser won't affect the passed style at all i added a `structuredClone` to the `OlRenderer`.
This also includes some minor refactoring.

Fix OlRenderer

---

docs/geoStylerContext.md
src/index.ts
styleguide.config.js

This adds a "GeoStylerContext" to the docs. It also adds a missing export of the `GeoStylerContextInterface`.

Add "GeoStylerContext" section to the docs

---

src/Component/Symbolizer/Field/ColorField/ColorField.less

This sets the color picker to full width in order to be consistent with other input fields.
Popup remains small:
closes https://github.com/geostyler/geostyler/issues/2290

fix: set ColorPicker to full width

---

src/Component/CodeEditor/CodeEditor.tsx

This adds the `onActiveParserChange` prop to the `CodeEditor`.
Fixes #2292

Add `onActiveParserChange` to `CodeEditor`

---

src/Component/BulkEditor/BulkEditor.tsx
src/Component/Style/Style.tsx
src/Component/Symbolizer/BulkEditModals/BulkEditModals.tsx
src/Component/Symbolizer/ColorMapEditor/ColorMapEditor.tsx
src/Component/Symbolizer/Field/ColorField/ColorField.less
src/Component/Symbolizer/Field/ColorField/ColorField.tsx

This adds a button to switch between `FunctionUI` and `ColorPicker` in the `ColorField`.
Fixes #2293

Add FunctionUI to `ColorField`

---

src/Component/Renderer/Renderer/Renderer.example.md
src/Component/Renderer/Renderer/Renderer.tsx

This readds the default value for the `rendererType` ("OpenLayers") of the `Renderer`. As the property is optional and there was not configure this is a bugfix.
It also adds an example of a `Renderer` with a `GeoStylerFunction`.

Readd OpenLayers as default rendererType

---

src/Component/Renderer/Renderer/Renderer.tsx
src/Component/Renderer/SLDRenderer/SLDRenderer.tsx

This moves the check for the required properties `wmsBaseUrl` and `layer` from the `Renderer` to the `SLDRenderer` component.
This is needed as the `Renderer` is not aware of the composed properties of the `SLDRenderer`.
Fixes https://github.com/geostyler/geostyler-demo/issues/507

Move thrown error to SLDRenderer

---

package-lock.json
package.json

This moves `antd` and `@ant-design/icons` from peerDependencies to regular dependencies. Since there is no actual exchange between instances (e.g. components) from an wrapping application to GeoStyler, there is no actual need to declare `antd` as peerDependency. This rather limits the possibilities of GeoStyler to be used in applications, as versions of antd have to match, if the wrapping application also uses antd.

chore(deps): move antd and @ant-design/icons to regular dependencies

---

src/Component/Symbolizer/LineEditor/LineEditor.tsx

This adds the graphicFill and graphicStroke fields of the `<LineEditor>` to the composition context.
Example with disabled graphicFill and graphicStroke fields:

feat: add LineEditor graphicFill and graphicStroke to composition

---

.github/workflows/release.yml
package.json

This removes the unnecessary `build` step in the release pipeline. This step is unnecessary, as we already create a build when publishing via the `prepublishOnly` script.
This also removes the building of the styleguide in the release pipeline, as it is not needed there.
This also fixes running parallel builds following the specs provided by https://docs.coveralls.io/parallel-builds

ci: remove styleguidist build and duplicate build step in release action

---

src/Component/ExpressionInput/BooleanExpressionInput/BooelanExpressionInput.spec.tsx
src/Component/ExpressionInput/BooleanExpressionInput/BooleanExpressionInput.tsx
src/Component/FunctionUI/FunctionUI.tsx
src/Component/Symbolizer/Field/VisibilityField/VisibilityField.tsx
src/locale/de_DE.ts
src/locale/en_US.ts
src/locale/es_ES.ts
src/locale/fr_FR.ts
src/locale/hr_HR.ts
src/locale/locale.ts
src/locale/zh_CN.ts

The checkbox in `<BooleanExpressionInput` was replaced with a switch.
BREAKING CHANGE: Following props of  `<BooleanExpressionInput>` changed: `label` was replaced with `labelOn` and `labelOff`. `checkboxProps` was renamed to `switchProps` and now accepts the properties of antd `<Switch>`.
Boolean `Visibility` in Editors:
Boolean `global` in ExpressionInput:

feat: replace checkbox with switch for boolean fields

---

src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/FillEditor/FillEditor.tsx
src/Component/Symbolizer/IconEditor/IconEditor.tsx
src/Component/Symbolizer/LineEditor/LineEditor.tsx
src/Component/Symbolizer/MarkEditor/MarkEditor.tsx
src/Component/Symbolizer/RasterEditor/RasterEditor.tsx
src/Component/Symbolizer/TextEditor/TextEditor.tsx
src/locale/de_DE.ts
src/locale/en_US.ts
src/locale/es_ES.ts
src/locale/fr_FR.ts
src/locale/hr_HR.ts
src/locale/locale.ts
src/locale/zh_CN.ts

This moves the visibility field to the editors and adds the visibility fields to the geostyler composition context.
`visibility: false`
`visibility: true`

feat: add editor visibility field to composition

---

src/Component/BulkEditor/BulkEditor.less
src/Component/BulkEditor/BulkEditor.tsx
src/Component/DataInput/WfsParserInput/WfsParserInput.tsx
src/Component/Filter/AttributeCombo/AttributeCombo.tsx
src/Component/RuleFieldContainer/RuleFieldContainer.tsx
src/Component/RuleGenerator/RuleGenerator.tsx
src/Component/StyleFieldContainer/StyleFieldContainer.tsx
src/Component/Symbolizer/ColorMapEditor/ColorMapEditor.tsx
src/Component/Symbolizer/Editor/Editor.tsx
src/Component/Symbolizer/Field/ChannelField/ChannelField.tsx
src/Component/Symbolizer/Field/GrayChannelField/GrayChannelField.tsx
src/Component/Symbolizer/Field/RgbChannelField/RgbChannelField.tsx
src/Component/Symbolizer/FillEditor/FillEditor.tsx
src/Component/Symbolizer/GraphicEditor/GraphicEditor.tsx
src/Component/Symbolizer/IconEditor/IconEditor.tsx
src/Component/Symbolizer/LineEditor/LineEditor.tsx
src/Component/Symbolizer/MarkEditor/MarkEditor.tsx
src/Component/Symbolizer/PropTextEditor/PropTextEditor.tsx
src/Component/Symbolizer/RasterChannelEditor/RasterChannelEditor.tsx
src/Component/Symbolizer/RasterEditor/RasterEditor.tsx
src/Component/Symbolizer/TextEditor/TextEditor.tsx
src/Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor.tsx
src/Util/FormItemUtil.spec.ts
src/Util/FormItemUtil.ts

This wraps the form items in `<BulkEditor>` into a `<Form>` and sets its layout to `'vertical'` so that the form layout will be consistent with all the other forms. It also adjusts the layout of the symbol selection.

fix: set vertical layout in BulkEditor

---

src/Component/CodeEditor/CodeEditor.tsx

Fixes reading mapbox style instead of string

fix: code editor onchange string to mapbox style

---

package-lock.json
package.json
src/Component/Symbolizer/Field/ColorField/ColorField.example.md
src/Component/Symbolizer/Field/ColorField/ColorField.less
src/Component/Symbolizer/Field/ColorField/ColorField.spec.tsx
src/Component/Symbolizer/Field/ColorField/ColorField.tsx

This fixes some issues with the ColorPicker: Compare #2501 
- allow RGB/HSB mode
- hide alpha inputs via API not via CSS
- ensure value of onChange is always in hex format
It also updates @ant-design/icons
Fixes #2501

Fix color picker

---

src/Component/Rules/Rules.tsx

This removes the unused `showAmount` and `showDuplicates` props from the `Rules` component.
The visibility of these fields can be configured via `Rule` in the GeoStyler composition context.
This closes #2466

Remove unused props

---

package-lock.json
package.json

* chroma-js introduced breaking changes in newer versions after `2.4.2` which is currently specified in the package.json (^2.4.2).
* I reported the issue to chroma-js here: https://github.com/gka/chroma.js/issues/367 
* Projects depending on geostyler cannot be build currently as the `^` is allowing newer minor versions of chroma-js (despite using e.g. version resolution from yarn: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)
* Renovate had also issues with it: https://github.com/geostyler/geostyler/pull/2519

chore: Pin chroma-js to 2.4.2

---

src/Component/Renderer/OlRenderer/OlRenderer.tsx

This cleans up the ol instance when destroying `<OlRenderer>`. This impurity became visible by using GeoStyler with react's StrictMode.
before:
after:

fix: cleanup ol instance when destroying <OlRenderer>

---

package.json
scripts/add-extensions.js
tsconfig.json

This adds a postbuild script that adds file extensions to the import pathes in the build output. Unfortunately there is no option in TypeScript where you can have imports without file extensions in the source code, but with file extensions in the build output.

Adds postbuild script to add file extensions

---

package-lock.json
package.json

Upgrade the geostyler-sld-parser dependency to version 8.1.0 to incorporate the latest features and improvements.

Update geostyler-sld-parser to version 8.1.0

---

src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.css

correction of the height of renderer in symbolizer editor

fix: height renderer in symbolizer editor

---

src/Component/NameField/NameField.tsx
src/Component/Style/Style.example.md
src/Component/Style/Style.tsx

We have an use case where we don't want to let the user change the name of the style and handle it ourselves (because the name of the style must correspond to the name of the data). 
I've added disableName (optional) in StyleComposableProps, false by default in Style
This option disable or not the name input of the style.

feat: add option to disable name #2618

---

.gitignore
package.json
vite.browser.config.ts

Include the browser build output directory in the package configuration and update the build settings accordingly.

Add browser build to package

---

vite.browser.config.ts

Adjust the browser build configuration to disable sourcemaps and define react and react-dom as external dependencies. Set the production environment variable for the application.

Update browser build configuration
